### ISSUE TITLE
Many spam entries on form

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#169] opened 2019-05-24 10:19 UTC
On a site with Umbraco v8.0.1 and Umbraco Forms 8.1.0 on a contact form, the client get many spam entries, even reCAPTCHA v2 is configurated and enabled on the form.

![image](https://user-images.githubusercontent.com/2919859/58321184-c671aa00-7e1d-11e9-8f9c-1774dbcc16de.png)

![image](https://user-images.githubusercontent.com/2919859/58321326-249e8d00-7e1e-11e9-8a70-14e8158d154c.png)

**Comment by clausjensen** [comment] 2019-05-31 10:49
If reCAPTCHA is enabled and confirmed to work - there's not really a whole lot we can do about this unless you can highlight something specific for us to look into in order to prevent further spam entries.
I'll close the issue for now, but it can be reopened if there's suggestions.

**Closed by clausjensen** 2019-05-31 10:49 UTC

**Comment by bjarnef** [comment] 2019-05-31 10:54
@clausjensen I can't see how Umbraco Forms validate using reCaptcha,  but it also validate on server side right? Otherwise bots might bypass the reCaptcha client side validation.

**Comment by bjarnef** [comment] 2019-05-31 11:02
It would also be great if Umbraco Forms in some way could mark form entries as spam or least easier clear all or all filtered form entries from backoffice. At the moment the easiest way to solve this is to create a copy of the form which doesn't copy the form entries. You then have to remember to pick the new form in content section and finally delete the old form.

**Comment by clausjensen** [comment] 2019-05-31 11:37
@bjarnef Forms is doing serverside reCAPTCHA as well as the clientside stuff so you cannot bypass it simply by working around it in the frontend.

@bergmania mentions you could look into implementing reCAPTCHA v3, but as I understand, it is a far more complicated solution requiring you to implement something on your entire site to detect bot behavior.

**Comment by bjarnef** [comment] 2019-06-12 11:57
@clausjensen does it make a different whether the field (using reCaptcha v2) is set to mandatory or not?
The reCaptcha client side validation is triggered if submitting form and not you not have the checked the reCaptcha checkbox (even when the field is not set as mandatory).

Maybe it in a future version could be possible to blacklist emails or email domains in general settings from Forms section in backoffice?

**Comment by clausjensen** [comment] 2019-06-12 12:46
We just tested it and it seems like it is still run serverside even with the clientside javascript disabled - when using checked/unchecked mandatory.

Regarding the backlisting - it's not a bad idea. But is it really solving the problem?
I would think that most of these spamming bots would not use a consistent email address or even email domain for exactly this reason, anyways?

**Comment by nul800sebastiaan** [comment] 2019-06-12 13:10
Just my 2 cents: we can see on the forums that people create spam accounts manually. We tried all kinds of lists and filters but none of them worked because it is too cheap to just hire a dozen people and make them send the spam by hand.

This is why we manually approve each new account that posts for the first time, usually they immediately start out with a link to whatever they're selling. 

The problem with ReCaptcha of course is that this also doesn't catch manual spammers who patiently click through each and every "traffic light", "store front", "bus" picture to get to leave a comment. As soon as they get through a Captcha check once they have a time period where they can actually keep going for a while before the Captcha needs to be checked again. I believe you might be able to configure this to be more strict though, to slow them down. Of course that would be bad for the user experience of end-users who have good intentions.

Unfortunately, the only good solution I see at the moment is to manually approve each incoming item.

**Comment by bjarnef** [comment] 2019-06-12 13:13
Okay, not sure how, but it seems these entries pass through with reCaptcha v2 added.

![image](https://user-images.githubusercontent.com/2919859/59353721-e3fea900-8d23-11e9-8dd2-fa2afc4338cc.png)

I have also tried set it to most secure some time ago, but still many entries the last couple of days.

![image](https://user-images.githubusercontent.com/2919859/59353799-14dede00-8d24-11e9-8bee-1d2c168e4acd.png)

Actually in this case it would help to blacklist the domain `@motorza.ru`
If the emails / email domains are blacklisted, it should then not create the form entries and trigger the workflows.

![image](https://user-images.githubusercontent.com/2919859/59353599-a3069480-8d23-11e9-91cd-6354de007c01.png)

**Comment by bjarnef** [comment] 2019-06-12 13:29
@nul800sebastiaan I have some time ago changes reCaptcha v2 checkbox from default security (in the middle) to most secure, but still on June 12th about 100 spam entries.

**Comment by bjarnef** [comment] 2019-07-31 07:14
It would be great if Umbraco Forms had a setting to blacklist specific emails or email domains via a config or similar.

E.g `xxx@motorza.ru` or `@motorza.ru` (or maybe using a wildcard to match all emails on the email domain, e.g. `*@motorza.ru`.

This should probably be a global configuration for blacklisting, which applies to all forms.

**Comment by bjarnef** [comment] 2019-09-18 13:42
@clausjensen do you have an example of a SQL script to delete many form entries with e.g. `@motorza.ru` in email?

**Comment by clausjensen** [comment] 2019-09-26 06:27
@bjarnef it's a little bit more complicated than that :)
Data is stored in a normalized format in the database, spread over the tables: `UFRecords`, `UFRecordFields` and `UFRecordDataXXXXX` (where xxxxx is the type of data stored).

Apart from that it is also stored in a denormalized JSON format in the `RecordData` column of `UFRecords`.

So in order to remove specific entries, you should be cleaning up rows in all of these tables - and not only the `UFRecords` table. As to how to find the specific entries you want to clean - it is most likely easier and less prone to errors, to find them by searching in the normalized tables. It should be easier to query this (and likely also less taxing to the database), than to query a stored JSON object in `RecordData`.

**Comment by bjarnef** [comment] 2019-09-26 06:39
@clausjensen okay, I may try that. With 17K entries and only a few real entries it would almost be easier to delete the form a re-create it, although you will then loose these few form entries. Unfortunately there is no "delete all except these entries" function.

This project is running with Umbraco v8.1.1 Umbraco Forms v8.1.1 and has reCaptchaV2 added.
It would be really useful be useful to configurate email domains to blacklist like `@motorza.ru`.

It would not prevent all spam since some on these have email domain `@gmail.com` but it would limit the number of spam entries.

**Comment by clausjensen** [comment] 2019-09-26 09:33
Unless you have a specific need for keeping these few entries in the Forms database, I would also suggest you just exporting them to whatever storage you use .. and then wipe the form and start over, instead of trying to clean up.

Yes it would be useful with a blacklist feature, but it is not something we have plans for doing at the moment.
