### ISSUE TITLE
Deploy/Forms content picker saves ID instead of UDI

### ISSUE THREAD

**Issue by ArnoldV** [umbraco/Umbraco.Forms.Issues#191] opened 2019-07-18 12:45 UTC
Deploy/Form issue

When using the content picker type in the form the Root node is saved as an id instead of an Udi, so when the form is transferred between environments it will not work anymore.

**Comment by bergmania** [comment] 2019-07-19 11:35
Hi @ArnoldV ..

The underlying issue is the same as for #190.

Duplicate of #190.

The issue is basically because the settings on prevalues and workflows are mapped as a reference type and not as a clone.

Therefore weird stuff happens, when deploy want to update the int to a Uid, it also updates on the forms model (due to the same reference).

**Closed by bergmania** 2019-07-19 11:35 UTC
