### ISSUE TITLE
RecordService.Delete triggers workflows that refer non deleted record

### ISSUE THREAD

**Issue by ArnoldV** [umbraco/Umbraco.Forms.Issues#198] opened 2019-08-05 09:26 UTC
When creating a custom workflow where you delete a record a YSOD shows and the following callstack shows that after the delete of a record the workflows are called again referecing a now deleted record.

It crashes when using this code in the workflow:

`record.State = Umbraco.Forms.Core.Enums.FormState.Deleted;`

or/also:
`var recordService = new RecordService();
recordService.Delete(record, record.GetForm());`

Since this code seems to be called async from Forms Core it can't be worked around by us.

`Object reference not set to an instance of an object.]
   Umbraco.Forms.Data.Storage.RecordFieldStorage.GetAllRecordFields(Record record, Form form) +137
   Umbraco.Forms.Data.Storage.RecordStorage.GetRecord(Object id, Form form) +330
   Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(List`1 workflows, RecordEventArgs e) +1688
   Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(Record record, Form form, FormState state, Boolean editMode) +238
   Umbraco.Forms.Web.Services.RecordService.Delete(Record record, Form form) +385`

---
_This item has been added to our backlog [AB#2214](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2214)_

**Comment by nul800sebastiaan** [comment] 2019-08-08 18:25
Thanks @ArnoldV - looks like a bug!

Out of curiosity, what are you using the Delete functionality for in this case?

**Comment by ArnoldV** [comment] 2019-08-08 18:45
We use Umbraco Forms to let people vote. We check their email and/or IP address and if they already voted there record will be deleted in one of the workflows. Currently we just replace all the voting info with emtpy strings.

**Comment by nul800sebastiaan** [comment] 2019-08-20 12:14
This looks like a duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/136 - can you confirm which versions you're using @ArnoldV

**Closed by nul800sebastiaan** 2019-08-20 12:14 UTC
Labels: state/estimation

**Comment by ArnoldV** [comment] 2019-08-21 12:48
@nul800sebastiaan seems indeed to be a duplicate. Using latest version (cloud project)

**Comment by nul800sebastiaan** [comment] 2019-08-21 13:07
@ArnoldV Thanks! v7 or v8, that's the big question? 😁

**Comment by ArnoldV** [comment] 2019-08-21 13:09
@nul800sebastiaan ah! actually a v7 project this time!
