### ISSUE TITLE
Anti-Forgery - Consider changing validation failure to INFO or WARN rather than ERROR

### ISSUE THREAD

**Issue by c9mb** [umbraco/Umbraco.Forms.Issues#847] opened 2022-08-19 22:13 UTC
Umbraco-Forms 7.5.9 on Umbraco-Cloud 7.15.7

Currently, when a submission fails to validate the Anti-Forgery token, it throws an application error, presumably as an easy way to abort the submission. 

I recently implemented code to refresh the Anti-Forgery token after the client has loaded the document, using javascript, so I could use partial caching on forms, and this appears to work as expected with interactive users having no issues submitting form entries.

However, with spambots auto-filling forms, this has seen my apparent 'errors' expand, as the 'bot' log entries change 
from: 
`INFO Umbraco.Forms.Core.Providers.FieldTypes.Recaptcha3 - The g-recaptcha-response hidden field for reCAPTCHA v3 is missing/empty and thus unable to be verified`
to:
`ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Web.Mvc.HttpAntiForgeryException (0x80004005): The anti-forgery cookie token and form field token do not match.`

Given that this is a validation and rejection process of the submission, rather than an actual application error, should not the failure to validate Anti-Forgery be handled the same way as failure to validate the g-recaptcha-response token ? i.e. an INFO message and cancelling of the submission

**Comment by AndyButland** [comment] 2023-03-01 09:38
I'm afraid we are no longer working on Forms 7 other than dealing with any security related issues, following the [Umbraco 7 end of life schedule](https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/umbraco-7-end-of-life-eol/) (which took this version into the security-only phase from July 2021).  Hence at this stage we'll close this issue.

Of course if the problem is found on a later version, please feel free to open a new issue indicating the versions affected.

In this case though, it looks like the error is bubbling up from the CMS rather than Forms - see the `Umbraco.Core.UmbracoApplicationBase` in the error message - so it would need to be amended there.

**Closed by AndyButland** 2023-03-01 09:38 UTC
