### ISSUE TITLE
Uninstall readme formatting error

### ISSUE THREAD

**Issue by rhealefever** [umbraco/Umbraco.Forms.Issues#87] opened 2019-02-22 09:11 UTC
Running a local version of Umbraco `8.0.0-alpha.2503`

The package readme while installing is formatted correctly:
![2019-02-22_1003](https://user-images.githubusercontent.com/47108275/53231776-017f0880-368a-11e9-9bcd-cac4c4cf4e5b.png)

But the package readme during uninstallation is not:
![2019-02-22_0942](https://user-images.githubusercontent.com/47108275/53231758-faf09100-3689-11e9-81a2-4475f249a40f.png)

I tested multiple other packages and all of them were formatted correctly. Umbraco Forms is the only package to my knowledge that does this.

**Comment by bergmania** [comment] 2019-02-27 08:12
Hi @rhealefever . Thanks for reporting

The issue is in Umbraco CMS.

Fixed in https://github.com/umbraco/Umbraco-CMS/commit/f2d7ed69ca0ddaba15138e8c3e9e0497819bd338

**Closed** 2019-02-27 08:13 UTC
