### ISSUE TITLE
Data loss issue with Forms 8.5.3

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Forms.Issues#412] opened 2020-09-29 19:27 UTC
A brief description of the issue goes here.

Data entries in the submissions are changed to <empty> if you select several entries and approve them

Reproduction
------------
### Bug summary
Forms 8.5.3 have a data loss issue with approving submissions where they disappear if you approve several at once.

The workaround here is to either not select several or just not approve them at all.

### Specifics

Umbraco 8.6.4 with Umbraco Forms 8.5.3.
Can be reproduced with an entirely fresh install.
I used the starter kit, just to get some content to faster render the form there.

### Steps to reproduce

Open VS and create a blank ASP.Net web application
Install Umbraco via Package Manager
Install Umbraco Forms via Package Manager
Build and run the project; keep all defaults during installation so you end up with a working install against a localdb with a starter package installed
Create a form – e.g. here’s my test form:
 
![image](https://user-images.githubusercontent.com/56826332/94604994-c054ce80-0298-11eb-84ab-ec2e3abf66cb.png)

Insert the form on a page via a macro and make several submissions
Go to the back office Forms section and select multiple submissions:

![image](https://user-images.githubusercontent.com/56826332/94605389-5852b800-0299-11eb-8fd9-c6dab781e0cc.png) 

If you click “Approve” with more than a single submission selected at least one field on one record will display <Empty> after submission:

 
![image](https://user-images.githubusercontent.com/56826332/94605431-66083d80-0299-11eb-96cf-ade5a96dcc5d.png)

It seems to all selected submission except for the last one to lose data.

### Expected result

The submission isn't deleted.

### Actual result

Well, the submission is deleted.

---
_This item has been added to our backlog [AB#8725](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8725)_

**Comment by nul800sebastiaan** [comment] 2020-10-05 12:51
Thanks for the report, I can confirm that this has been an issue since the release of 8.4.0 in March (8.3.2 works fine). Surprised it hasn't been noticed before. We'll have to look into this soon.

**Comment by RyuLindow** [comment] 2020-10-05 12:54
Awesome, thanks!

**Comment by nul800sebastiaan** [comment] 2020-10-15 16:42
This is now fixed for the upcoming version 8.5.4.

**Closed** 2020-10-15 16:41 UTC
Labels: state/sprint-candidate, status/regression, type/bug

**Comment by ronaldbarendse** [comment] 2020-10-23 10:31
For those that have encountered this issue, it might be worthwhile to check if the data is still available in either the `UFRecords.RecordData` column or as seperate rows in the `UFRecord*` tables.
