### ISSUE TITLE
Editing a Form on Front End with Conditional Fields

### ISSUE THREAD

**Issue by KarlButler1** [umbraco/Umbraco.Forms.Issues#213] opened 2019-08-27 11:22 UTC
**Specifics:**
**Umbraco Forms:** 7.1.2
**Umbraco CMS:** 7.15.1

**Issue:** When editing the form the conditional fields on the form will not work. 
**Expected Outcome:** We have a checkbox when this is set to true this should cause a text field to be displayed. 
**Actual Outcome:** When the checkbox is set to true, the text field is not displayed

**Steps to Replicate the issue:** 
1. Install Umbraco Forms 7.1.2 
2. Set config value in the UmbracoForms.config to `key="AllowEditableFormSubmissions"` `value="True"`
3. Create a form on the front end, we are currently using the following code to call this form: `@Umbraco.RenderMacro("renderUmbracoForm", new { FormGuid = Model.Content.ApplicationForm, FormTheme = "bootstrap3-horizontal", ExcludeScripts = "0"})`
4. When using the conditional fields on the form when creating this, the conditional fields will work as expected 
5. Edit this form by clicking on the link on the profile page, this will take you to the form with the URL displayed as http://domain/?recordId={{formGuid}} 
We are using the following code to render the edit form: `@Umbraco.RenderMacro("renderUmbracoForm", new { FormGuid = Model.Form.Id, FormTheme = "bootstrap3-horizontal", ExcludeScripts = "1", AllowEditing = "1"})`
6. Click on the checkbox to enable the conditional field, a text box should then be displayed

**Notes around the issue:** 
- I'm not seeing any errors in the inspect window in the console and in the logs regarding why the conditional fields are not working 
- I believe it could be due to the `excludeScripts` value being set as 1 on the edit form, and this means that the conditional fields can't be recognised / functionality doesn't work 
- I've tried setting the excludeScripts value to 0, but I'm getting a YSOD as attached as error.png below 
- I've looked into this error and it seems to be complaining about a null value on the following method ( Line 14: `Model.GetFieldsNotDisplayed()` ) in the `script.cshtml` file 

Please could you take a look at this for me and please let me know if you have any questions or if you need anymore info. 

[StackTrace.txt](https://github.com/umbraco/Umbraco.Forms.Issues/files/3545817/StackTrace.txt)

Kind regards, 
Karl

**Comment by warrenbuckley** [comment] 2019-08-27 12:14
Hi @KarlButler1 
I have been unable to reproduce this in a clean Umbraco 7.15.1 site with the starter kit installed and the 7.1.2 Forms version

Can you clarify your repro steps please on a clean Umbraco site to ensure it not anything else.
Let me know how you get on.

Also if you can I would like a copy of the form JSON on disk to help me debug, to see if its a specific combination of fields & conditional rules that is causing this problem

Thanks
Warren :)

**Comment by KarlButler1** [comment] 2019-08-27 12:24
Hi @warrenbuckley, 

Thanks for your response on this, I'll look to reproduce my steps on a fresh install and see how it goes and report back soon.

I'll check with the team to see if I'm able to supply the form JSON from disk.

Thanks,
Karl

**Comment by KarlButler1** [comment] 2019-08-27 13:20
Hi @warrenbuckley, 

Have you got an email I can send the JSON file of the form over to ? 

The conditional fields are mostly made up of a "checkbox" , being set to true and then using this to display "Short Answer" fields

**Comment by nul800sebastiaan** [comment] 2019-08-27 14:40
@KarlButler1 You can go for warren@umbraco.com please! 👍 Thanks!

**Comment by KarlButler1** [comment] 2019-08-28 07:57
Good Morning @warrenbuckley @nul800sebastiaan, 

I've sent the Form JSON over to the email provided

**Comment by warrenbuckley** [comment] 2019-08-29 10:33
Hello @KarlButler1 
We have pushed a fix and here is a nightly/CI build for you to test with, but this should fix your problem (will send them via email)

Thanks,
Warren

**Comment by KarlButler1** [comment] 2019-08-29 11:52
Hi Warren,

Thanks for all our help on this, I've just tested the nightly build locally on this project and all is now working as expected. 

Thanks, 
Karl

**Closed** 2019-09-25 10:55 UTC
Labels: release/7.2.0, release/8.2.0
