### ISSUE TITLE
Option to add reply-to address

### ISSUE THREAD

**Issue by mastrup** [umbraco/Umbraco.Forms.Issues#51] opened 2018-11-28 08:58 UTC
On the standard workflows "Send email" and "Send email with template (Razor)" it would be nice if a Reply-to field was added. Currently we have some clients that uses magic strings in the sender field, to set the email from the person who fills out the form.
When doing that, the email often gets caught in a SPAM filter since the SMTP server isn't added to the SPF.

I was thinking something like this: [https://i.imgur.com/fijvViN.jpg](https://i.imgur.com/fijvViN.jpg)

**Comment by nul800sebastiaan** [comment] 2018-12-18 12:12
Makes sense! While this is not available, we would encourage you to build your own workflow, but it would be super nice to have this built-in out of the box.

**Comment by ronaldbarendse** [comment] 2019-08-23 11:55
Even if this isn't shipped out of the box, the built-in `SendEmail` and `SendRazorEmail` workflow types could be opened up by adding some virtual methods for building the HTML, setting the `MailMessage` properties and sending it (using `SmtpClient`).

That way, creating your own workflow would be a lot easier, especially if you just want to add a single setting: just inherit the built-in workflow type and override the correct method to apply it...

**Comment by ronaldbarendse** [comment] 2020-08-19 13:04
Looks like this option is now added (and tracked in a duplicate issue: https://github.com/umbraco/Umbraco.Forms.Issues/issues/357):

![Send template mail](https://user-images.githubusercontent.com/1051287/90637731-a7361800-e22c-11ea-833c-ee7af73402d4.png)

The label could be updated to 'Reply-to email', as it currently looks like it's using the property name (in PascalCase).

**Comment by richarth** [comment] 2020-12-10 10:41
Hi,

It looks like this isn't available in v7 of Forms.  Is there any chance it could be backported please?

**Comment by xrasod** [comment] 2021-01-08 14:02
Yes, a backport would be great frankly. Would save me a lot of work.

**Comment by mastrup** [comment] 2021-03-31 07:12
With the Umbraco Forms 8.7 RC I think that this should be taken into consideration, since you are also [adding options for CC and BCC addresses in workflow emails](https://github.com/umbraco/Umbraco.Forms.Issues/issues/457).

**Comment by AndyButland** [comment] 2021-03-31 08:11
Hi @mastrup - I believe this is already available (see the comment from ronaldbarendse above).

Here's what I see in 8.7:

![image](https://user-images.githubusercontent.com/1993459/113112320-56968c80-9209-11eb-95c3-43dbe0cc9fa1.png)

Looks like this issue is actually a duplicate of #357, which has been closed, so think this one can be too.

**Closed by AndyButland** 2021-03-31 08:11 UTC
Labels: project/mail, status/idea, type/feature
