### ISSUE TITLE
Changes to field mapping not saved

### ISSUE THREAD

**Issue by RBerntsen** [umbraco/Umbraco.Forms.Issues#414] opened 2020-10-01 08:49 UTC
When creating a workflow with field mapping and afterwards editing either alias or static values these are not saved. Only way to fix this is to remove the field and re-add it.

I don't think this is a duplicate of #350 and #360 as this is about updating values but they're definitely related.

Reproduction
------------

### Specifics
Tested on clean installation of Umbraco 8.7 and Umbraco Forms 8.5.3.
I found the bug on Umbraco 8.6.4 and Umbraco Forms 8.4.1

### Steps to reproduce
Create a new form and add two fields:
![image](https://user-images.githubusercontent.com/1783382/94786133-dc5b8b80-03d0-11eb-9a98-3a7b51c65c63.png)

Add a workflow of e.g. type "Send form to URL"
![image](https://user-images.githubusercontent.com/1783382/94786413-3bb99b80-03d1-11eb-95f9-aec748b9feb6.png)

Save these changes by clicking submit and then save the form. Now go back and edit the field mapping, save the workflow, save form. Go back once again to the field mapping and see the changes are not there:
![image](https://i.imgur.com/ShknE1B.gif)

### Expected result
I would expect the changes to be saved.... :)

### Actual result
The changes are not saved and the only way to "update" the field mapping is to remove a field and add it again.

**Comment by nul800sebastiaan** [comment] 2020-10-07 13:46
That is annoying! Yes, closely related to those other two issues but a new one indeed. I will encourage you to keep using the workaround for now.

**Comment by RBerntsen** [comment] 2020-10-08 07:12
@nul800sebastiaan And by the workaround you mean to remove the field mapping and re-add it, right?

**Comment by thenexus00** [comment] 2020-10-14 04:04
> That is annoying! Yes, closely related to those other two issues but a new one indeed. I will encourage you to keep using the workaround for now.

There seems to be 3 related issues around mapping:
- Static value never saves (I had a look at the Angular side and does not appear to be an issue here)
- Last item does not save unless you add empty
- Single item does not save if you edit it unless you hit add blank button or edit something else as well

Any ETA on when any of these will be fixed as they seem to be in some form since May now.

**Comment by HTDL-Andrew** [comment] 2020-10-16 09:27
I can get the static values to save but when testing the send to URL these values are never posted. I've had to change these values to hidden fields so the data is sent and the API I am using has the correct information. The only issue is a key-value the API requires is exposed in the HTML source so not an ideal solution.

I've had mixed success with adding a blank mapping, so I've personally found deleting the workflow item and adding from scratch is the only way I can add this.

The biggest issue is the problems this causes between us (The agency) and our clients as we have had to liaise with the API / CRM company to narrow down what this issue is, set up an external server to see what is actually being posted etc. So I would urge this to be looked at ASAP as clients rely on this connectivity for their businesses.

**Comment by dangander** [comment] 2020-10-28 15:26
Confirmed this on Umbraco 8.8.1 with Forms 8.5.4 where the suggested workaround seems to also trigger the bug issue #407 - see my screen recording there for repro.

As @HTDL-Andrew said, this is a major sticking point for system integration like CRMs so really needs prioritising I think, especially since it seems to completely invalidate the form json file too, requiring us to delete the (now invalidated) form, recreate it, change all the content items containing the old form, and lose all the entry history too.

@nul800sebastiaan - any updates or ETA on this yet?

**Comment by dangander** [comment] 2020-12-16 10:49
Still present on in 8.9.0 with Forms 8.5.5.
Editing the mappings after they've been saved the first time also causes #407 so that issue may need reopening too.

**Closed** 2021-02-02 11:59 UTC
Labels: project/workflows, state/needs-investigation, type/bug

**Comment by bruno-casari-shout** [comment] 2021-03-16 11:40
Was this issue ever fixed? It's been on the backlog for a while now and it does not appear to have been fixed.

This is a very fundamental bug that needs to be addressed asap.

**Comment by AndyButland** [comment] 2021-03-16 11:53
Hi @bruno-casari-shout - yes, this is resolved in the upcoming release 8.7.0 (I've just added the tag that was missing).  We're aiming to get an RC out for this release next week..

**Comment by bruno-casari-shout** [comment] 2021-03-16 14:37
Could a hot fix be applied to version 8.5.*?

**Comment by AndyButland** [comment] 2021-03-17 08:32
Not sure I can commit to that at the moment but if you can, in any case, I'd suggest looking to update to 8.7 when it's out.  There are [quite a few](https://github.com/umbraco/Umbraco.Forms.Issues/issues?q=label%3Arelease%2F8.7.0+) bug fixes planned to be in there, not just this one.
