### ISSUE TITLE
"Save as Umbraco content node" workflow has issues with uploading an image

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Forms.Issues#162] opened 2019-05-15 11:09 UTC
So this might be a possible bug or maybe the workflow is just not intended for this use. 

When you use the "Save as Umbraco content node" and upload an image to save on the node it will create the node just fine. However, the node will give this error when looking at it and the image will not be there.
![image](https://user-images.githubusercontent.com/42831978/57770002-989ab000-770f-11e9-8e7b-cc1a0a95cc97.png)

The image will be uploaded in the Media folder in a Forms folder so the image is successfully uploaded. But you won't be able to see it in the media section in the backoffice.

Reproduction
------------
### Bug summary
File is not available in the media section and can therefore not be used on the node. 

### Specifics
Tested on Cloud with: 
Umbraco 8.0.2
Forms 8.1.1

### Steps to reproduce
1. Create a node that has a property type which is a media picker
2. Create a Form and have an upload field using File upload property type
3. Add the "Save as Umbraco content node" workflow. Then select the property type on the node to be the File that is uploaded.
4. When you submit the form it won't give any errors. But going to the node in the backoffice you will see this error message and the image is not there:
```
Received an error from the server
An error occured
Multiple actions were found that match the request: 
 GetByIds on type Umbraco.Web.Editors.EntityController
 GetByIds on type Umbraco.Web.Editors.EntityController
 GetByIds on type Umbraco.Web.Editors.EntityController

Exception Details
System.InvalidOperationException: Multiple actions were found that match the request: 
 GetByIds on type Umbraco.Web.Editors.EntityController
 GetByIds on type Umbraco.Web.Editors.EntityController
 GetByIds on type Umbraco.Web.Editors.EntityController
Stacktrace
at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext)
   at System.Web.Http.Controllers.ApiControllerActionSelector.SelectAction(HttpControllerContext controllerContext)
   at Umbraco.Web.WebApi.ParameterSwapControllerActionSelector.SelectAction(HttpControllerContext controllerContext)
   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

### Expected result
To see the image on the node.

### Actual result
Error message and no image when checking the node

**Comment by bergmania** [comment] 2019-05-15 12:00
I think this is duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/156.

Thanks for the detailed description.

Forms file uploads are not stored a normal media. Therefore it does not make sense to use the media picker. You should be able to use the `File Upload` property in the content type.

**Comment by HalldorLyngmo** [comment] 2019-05-15 12:16
Yes, that's correct it's the same issue. I couldn't find anything earlier regarding the workflow name. You can close this one :)

**Closed** 2019-05-15 12:21 UTC
