### ISSUE TITLE
Cannot Delete Form Field

### ISSUE THREAD

**Issue by gabador-mof** [umbraco/Umbraco.Forms.Issues#426] opened 2020-10-14 16:45 UTC
Umbraco version 8.8.0, Forms version 8.5.3 

I have an issue where if I try to delete a form field, I cannot because the confirmation popup does not appear next to the delete icon. 

I can replicate this with a standard install of Umbraco, and a standard install of forms. 
![image](https://user-images.githubusercontent.com/64405523/96019857-cd0b2200-0e55-11eb-9b80-59fa3a6f57b7.png)

This is new in 8.5.3

Thanks!

**Comment by lynnewritescode** [comment] 2020-10-14 17:11
I am also having this issue:
![umbraco-forms](https://user-images.githubusercontent.com/4159464/96022369-aabed780-0e48-11eb-8035-0e5409e610f9.gif)

**Comment by thenexus00** [comment] 2020-10-15 00:18
I have a temporary fix.

**Inside:**
/App_Plugins/UmbracoForms/Directives/umb-forms-designer-new.html

**Find:**
```
<umb-confirm-action ng-if="field.deletePrompt"
    direction="left"
    on-confirm="removeField(fieldset, container, field)"
    on-cancel="hidePrompt(field)" data-umb="confirm_{{$parent.$parent.$index}}_{{$parent.$index}}_{{$index}}">
</umb-confirm-action>
```

**Replace with:**
<umb-confirm-action
   show="field.deletePrompt"
   direction="left"
   on-confirm="removeField(fieldset, container, field)"
   on-cancel="hidePrompt(field)"
   data-umb="confirm_{{$parent.$parent.$index}}_{{$parent.$index}}_{{$index}}">
 </umb-confirm-action>


Does not look pretty but it works.

The issues are around:
ng-if="field.deletePrompt"

And style stuff

**Comment by nul800sebastiaan** [comment] 2020-10-15 10:58
Thanks, this is a duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/391 - in short: the above workaround can be used until Umbraco 8.8.1 is out. Apologies for the inconvenience!

**Closed by nul800sebastiaan** 2020-10-15 10:58 UTC
