### ISSUE TITLE
Dropdown and Choice field types throws validation error when no options are selected

### ISSUE THREAD

**Issue by Alkaersig** [umbraco/Umbraco.Forms.Issues#250] opened 2019-11-21 10:28 UTC
After updating to Umbraco Forms 7.2.0 the Single Choice, Multiple Choice and Dropdown field types throws an validation error when no options are selected, even though the field is not marked as mandatory.

![image](https://user-images.githubusercontent.com/12032054/69333075-47d4b880-0c58-11ea-806e-03a5a551cda6.png)

Tested on clean installation with the same result. 

This is a big problem, especially since fields hidden behind conditions will throw invisible errors and break the form.

---
_This item has been added to our backlog [AB#3988](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3988)_

**Comment by Alkaersig** [comment] 2019-11-21 11:16
Just ran over all the "selection" field types and found that several types are affected by this issue. Also there seems to be a formatting problem with the multiple choice field type. This is tested on Umbraco Starter Kit, so i dont know if this issue is connected to the template, since we have a custom renderer that is not affected.

**Comment by Alkaersig** [comment] 2019-11-27 10:37
Is there an easy way to disable validation for these fields when "being empty"? Would hate to have to roll back to an older version of forms without this issue and 7.2.0 solved a lot of other issues we had.

**Comment by ashkrishan** [comment] 2019-11-27 13:45
> Is there an easy way to disable validation for these fields when "being empty"? Would hate to have to roll back to an older version of forms without this issue and 7.2.0 solved a lot of other issues we had.

One of my installtion using 7.2.0 faced this issue. To resolve I am using the prevalues Text files instead of harcoded prevalues from settings.

**Comment by bergmania** [comment] 2019-12-16 09:34
Duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/237

**Closed by bergmania** 2019-12-16 09:34 UTC
Labels: state/estimation, state/hq-discussion-forms
