### ISSUE TITLE
bracket syntax for replacing setting workflow settings with record values uses caption instead of alias

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco.Forms.Issues#35] opened 2018-10-17 10:10 UTC
This causes issues when you have 2 (or more) fields with the same name... you can never access the first value...

**Comment by nul800sebastiaan** [comment] 2018-11-20 16:01
Hey Tim, I am not sure how this works, can you give a few steps to reproduce the issue please?

**Comment by TimGeyssens** [comment] 2018-11-20 16:39
hey, there is a support call with all the details, let my find it and copy some steps

**Comment by TimGeyssens** [comment] 2018-11-20 16:40
support call 38700, Add a new form, create 2 fields with the same name (email type and email as name), update the email workflow to send to {email} instead of a harcoded address... fill in the form, it now send to the second email filled in, and you can't access the first email field with the special syntax

**Comment by TimGeyssens** [comment] 2018-11-26 08:15
@nul800sebastiaan  does it make sense? if you need more info let me know

**Comment by hfloyd** [comment] 2019-03-14 19:56
I think this is the same as the issue mentioned here on the old tracker: 
https://issues.umbraco.org/issue/CON-1208#tab=Comments

This is still a problem in Version 7.0.6.

For example, given two form fields:
![FormFields](https://user-images.githubusercontent.com/1252593/54386434-52719380-466f-11e9-8771-e102e4174470.png)

Ideally (and logically), one would use the field ALIAS as the "merge value":
![Email-DoesntWork](https://user-images.githubusercontent.com/1252593/54386500-7339e900-466f-11e9-9777-72c560a42c2e.png)

However, this results in blank values in the resulting email message.  (Neither casing as the Alias is cased nor making it all lowercase works.)

Based on the previously mentioned issue as well as this forum post: https://our.umbraco.com/forum/umbraco-forms/92172-unable-to-get-field-values-in-email-subject

I was clued into using the caption/field name instead. 

However, using it as-is DOES NOT WORK (it prevents the email from sending at all):
![DoesntWorkDoesntSubmit](https://user-images.githubusercontent.com/1252593/54386669-e0e61500-466f-11e9-94a2-cfeb989e9186.png)

You need to remove the spaces for it to work:
![ThisWorks](https://user-images.githubusercontent.com/1252593/54386725-0115d400-4670-11e9-84e3-19af76f2ef37.png)

This format (even with the question mark included) DOES cause the email to send with the expected values.
![image](https://user-images.githubusercontent.com/1252593/54386799-302c4580-4670-11e9-8c66-4387bb234847.png)

This is really not intuitive at all, and as previously mentioned, if you have two fields with the same user-visible names, you cannot target the specific field desired. Generally aliases are understood to be unique on a single form, so using the alias would allow for accurate targeting.

Also, it means that any changes to the user-visible wording for a field (certainly not unheard of!) will break any merge references.

I can understand that correcting an error of this type could create a breaking change -  after all, developers have likely figured out how to set up their merge references using the caption. My suggestion would be to use a check in the merging code along the lines of 

```
if (bracketedmergefield matches an alias of a formfield)
{ merge in field value}
else if (bracketedmergefield matches a caption of a formfield)
{ merge in field value}
else {blank}
```

I know there is still the slight possibility that someone might have an alias and a caption on the same form that match, but are assigned to different fields... but I really think this should be changed anyway - and mentioned in the release notes.

At the least, I hope this fix makes it into Version 8 immediately, since that is so new, you don't need to worry about legacy forms.

**Comment by TimGeyssens** [comment] 2019-03-21 14:36
Had a support call a while back and they said it wasn't a priority and that it would break existing workflows (offered a couple of solutions but didn't get a response back...)

**Comment by hfloyd** [comment] 2019-03-21 18:14
Hi @TimGeyssens , Yeah, I got that impression... It would be nice if this could at least get resolved for the V8 version... Even if there was a config value or something... <mergesource>caption/alias</mergesource> because it is just icky as-is... and can really cause issues for larger or more complex forms.

**Comment by nul800sebastiaan** [comment] 2020-03-03 16:02
This issue is duplicated in #120, we'll keep tracking it there ➡️ #120

**Closed by nul800sebastiaan** 2020-03-03 16:02 UTC
Labels: type/bug
