### ISSUE TITLE
Unable to delete fields in forms on 8.5.3

### ISSUE THREAD

**Issue by jonat123** [umbraco/Umbraco.Forms.Issues#421] opened 2020-10-13 16:43 UTC
It is not possible to delete fields from Umbraco forms, nothing happens when clicking the delete trash bin icon on the latest version of forms

Reproduction
------------

### Bug summary
If you want to delete a field from your Umbraco form, you will find out that it is not possible.

When you click the small trash bin icon to delete the field you will notice that nothing will happen, you won't get the small icons to delete it: 
![image](https://user-images.githubusercontent.com/54025331/95888191-1178be00-0d81-11eb-8cb0-22a569483562.png)

### Specifics
This has been tested on a new project upgraded to Umbraco 8.8 and Forms 8.5.3 and a newly created project on the latest versions and an on premise version with the same versions, where the same happens.

Tried to test it out in 8.6.5 and 8.4.1 where it works fine.

Looking into the code I can see that on the 8.4.1 project when clicking on the trash icon it runs the angular script and displays the div with the delete icons:
![image](https://user-images.githubusercontent.com/54025331/95889042-3883bf80-0d82-11eb-8251-d7f9c30b3f7c.png)

When doing the same on forms 8.5.3  the div class is there however it seems that it is missing the `ng-class="{ '-top': direction === 'top', '-right': direction === 'right', '-bottom': direction === 'bottom', '-left': direction === 'left'}"` and therefore does not show the delete icons.
![image](https://user-images.githubusercontent.com/54025331/95889633-ed1de100-0d82-11eb-846b-40d9521004bc.png)

### Steps to reproduce

1. Find or create a project running on 8.5.3
2. Create a new form or try to edit an existing one.
3. try and delete a field in the form.

### Expected result
Expected the delete icons to be displayed:
![image](https://user-images.githubusercontent.com/54025331/95888191-1178be00-0d81-11eb-8cb0-22a569483562.png)

and be able to delete the field from the form.

### Actual result
Nothing happens and the field will not be deleted.

**Comment by dangander** [comment] 2020-10-13 16:54
Confirmed this is happening with Umbraco 8.8 and Forms 8.5.3 - also unable to delete groups in a form.

**Comment by nul800sebastiaan** [comment] 2020-10-14 13:35
Thanks, this is a CMS issue and will be fixed once CMS 8.8.1 is out. Issue https://github.com/umbraco/Umbraco.Forms.Issues/issues/391 has some temporary workarounds, I'll close this as a duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/391

**Closed by nul800sebastiaan** 2020-10-14 13:35 UTC
