### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kows** [umbraco/Umbraco.Forms.Issues#47] opened 2018-11-19 09:04 UTC
On the settings tab of a form:

Captions
Add title and change captions for Submit, Next and **Previus** buttons

Styling
Add a class/Multiple classes to wrap **you** form to enable custom styling, disable default styling and load assets with client dependencies

Moderation
Allow form submissions to be post moderated. Most use cases are for publically shown entries such as blog post comments or **submisisons** for a social campaign

**Comment by nul800sebastiaan** [comment] 2018-11-20 14:48
Thanks for reporting! 👍

**Comment by bergmania** [comment] 2018-11-23 10:01
Duplicate of #32

**Closed by bergmania** 2018-11-23 10:01 UTC
Labels: state/backlog, type/bug
