### ISSUE TITLE
Change in umbracoforms.min.js makes same form two times on same page makes validation fail

### ISSUE THREAD

**Issue by runegronkjaer** [umbraco/Umbraco.Forms.Issues#1297] opened 2024-09-19 06:55 UTC
A change have been made to the /Assets/themes/default/umbracoforms.min.js file that is a problem when the same form is on the page two or more times.
The problem is that the validation triggers on both forms instead of only the one that the user is interacting with.

### Bug summary

Seems like a recent change in the umbracoforms.min.js have broken validation.

### Specifics

This is the file that is broken
https://www.athenas.nl/App_Plugins/UmbracoForms/Assets/themes/default/umbracoforms.min.js

Here's a live example:
https://www.athenas.nl/testingformspage/

Here's a screenshot of the change that has made the problem.
![umbracoforma-javascript-difference](https://github.com/user-attachments/assets/3845d601-6243-4467-9de8-49684ef9044f)

### Steps to reproduce

1. Create two of the same form on the same page
2. The last form will submit but the first one will not, because it validates the second form as well

### Expected result

The validation should be sandboxed to only the form that is being interacted with

### Actual result

Both forms validate when one is interacted with.

---
_This item has been added to our backlog AB#44160_

**Comment by AndyButland** [comment] 2024-09-19 08:45
Thanks for reporting this.  It looks like our fix for https://github.com/umbraco/Forms/pull/1053 has caused this regression.  We'll investigate a means of supporting two forms on the page as well as resolving the linked issue.

**Comment by LSkovlund** [comment] 2024-09-20 09:44
@AndyButland the form does not even have to be the same. I have updated the example - https://www.athenas.nl/testingformspage/ - if you try submitting Test Form 1, you will see that it validates a completely different form.

Another curious thing is that [athenas.nl](https://www.athenas.nl/) and [a-speakers.fr](https://www.a-speakers.fr/) are a part of the same cloud solution, and therefore both running "Forms 13.2.2" hower a-speakers.fr is at the moment of writing still loading the old script, and athenas.nl is loading the new script.

![image](https://github.com/user-attachments/assets/d746125b-a895-4567-b7f5-61a5903acf02)

![image](https://github.com/user-attachments/assets/e9558ceb-8b61-4b3b-ad1f-f0ee563f7dfd)

**Comment by TimBoonstra** [comment] 2024-09-24 09:24
Looking at the screenshot, i  think related to the issue i am experiencing with umbraco forms 13.2.3, if you have 2 forms on a page then the validation is (also?) triggered on the last form which makes the submit fail, (related to #1189  that was fixed in 13.1.1?)

**Comment by runegronkjaer** [comment] 2024-09-24 09:38
> Looking at the screenshot, i think this is related to the issue i am experiencing with umbraco forms 13.2.3, if you have 2 forms on a page then the validation is (also?) triggered on the last form which makes the submit fail, (related to #1189 that was fixed in 13.1.1?)

Sounds like the same problem yes.

**Comment by AndyButland** [comment] 2024-09-24 11:34
This will be resolved in the next patch release, that we'll look to get out on Thursday (and auto-upgrade on Umbraco Cloud next Tuesday).

**Closed by AndyButland** 2024-09-24 11:34 UTC
Labels: type/bug, state/sprint-candidate, release/14.1.4, release/13.2.4

**Comment by LSkovlund** [comment] 2024-09-25 08:59
@AndyButland https://athenas.euwest01.umbraco.io/home-nl/ and https://athenas.euwest01.umbraco.io/home-fr/ are part of the same cloud solution, but for a long while **home-fr** has kept working, and only today did it start loading the new script, while **home-nl** started using the new script back when we first reported this problem. We are puzzled about that part as well, and find it important because, when the update is out how can we make sure that the patched script starts loading immediately, and not at some delayed point in time?

**Comment by AndyButland** [comment] 2024-09-25 09:08
That does seem puzzling I agree.  All I can really say is that it sounds like somehow one page was getting a cached version, as you would expect both pages to be referencing the same file shipped in the Forms package.

You should see if you view source on a page with a form a reference to the file with a cache buster that corresponds to the current version you are running, e.g.

```
/App_Plugins/UmbracoForms/Assets/recaptcha.v3.init.min.js?v=13.2.4
```

Once you've upgraded, assuming you can see that in the source of both pages that should be enough to be sure you have the latest version of the file loaded.  If you don't, then maybe you have some HTML caching going on and that might then explain the discrepancy.
