### ISSUE TITLE
“validate as an email address” option allows invalid addresses.

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco.Forms.Issues#227] opened 2019-09-12 21:47 UTC
i.e. user@domain is accepted.

Documented in the previous issue tracker here https://issues.umbraco.org/issue/CON-1433 (i.e. description, expected, actual results etc), but still an issue in UF7.x

I appreciate the regex is customisable, but this is ticket is to fix the default expression and to help those content editors who don’t have/want any technical understanding of regex.

Thanks
Andrew

---
_This item has been added to our backlog [AB#2706](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2706)_

**Comment by gavinfaux** [comment] 2019-09-26 14:27
Duplicate of #208

**Closed** 2020-03-03 15:30 UTC
