### ISSUE TITLE
Recaptcha failing postbacks after confirming uses aren't robots

### ISSUE THREAD

**Issue by mmcconahay** [umbraco/Umbraco.Forms.Issues#252] opened 2019-12-09 15:02 UTC
When using recaptcha on forms for our www.flowcrete.co.uk website, the form is able to post back but then comes back with a failed verification from recaptcha after it was already verified on the client side. The form saves and sends out to who it needs to but doesn't go to the success page. Removing recaptcha lets the form work successfully but that isn't an option. Let me know if more information is needed. Any help is appreciated.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Bug happens when submitting a form with recaptcha. The form saves and sends an email but then is failed and never gets a success true so it doesn't go to the success page or show the success message. Taking out recaptcha lets the form process correctly. I've verified that both recpatcha keys in the config are correct.

### Specifics

Fill out form here: https://www.flowcrete.co.uk/contact-us/contact-form/
after submitting it returns to the form page with a recaptcha error.

### Steps to reproduce

Fill out form here: https://www.flowcrete.co.uk/contact-us/contact-form/
Submit and will be sent back to the form page with a failed recpatcha message but it still sends out emails and saves the form submission in the forms table.

### Expected result

Expect the form to submit to the success redirect page.

### Actual result

form is sent back tot he form page with recpatcha result.

**Comment by mov3nforward** [comment] 2020-01-29 14:23
The forms package seems to be very buggy. First we raised an issue about the attachments not working and we were told that it would be fixed in release 7.3. Now the Recaptcha doesn't work!?!? It did in version 7.1.1. We have a client that has been waiting 2 weeks for a fix. It is **EXTREMELY** frustrating that **NOTHING** in Umbraco seems to be tested before it is released. At this point we are looking to move away from Umbraco. It is one of the buggiest CMS we work with and it is only getting worse with each release.

**Comment by nul800sebastiaan** [comment] 2020-01-29 14:45
I can understand your frustration and in our defense, we do test things a lot, but it could of course always be better.

Let's focus on the issue at hand, I just tested the contact form above and was able to submit it immediately, so either it's been fixed or something is different on my end. 

We sometimes hear from people that this is a problem and it turns out that the config key wasn't updated, that could be the problem? https://our.umbraco.com/documentation/Add-ons/umbracoforms/editor/creating-a-form/fieldtypes/Recaptcha/

As far as I can tell, there's been 2 reports of Recaptcha not working properly, out of many many people using it successfully, so it seems to have something to do with your local setup, but it's hard to tell if we can't reproduce the problem.

**Comment by nul800sebastiaan** [comment] 2020-01-29 15:13
Just to make sure, I've tested this on 7.15 + Forms 7.3 and it's indeed a bug (I don't think @mmcconahay would be on that version, which is why the issue might be fixed there already. 

I've sent it to the team to look at soon, will keep you posted!

**Comment by nul800sebastiaan** [comment] 2020-01-29 15:18
And just to confirm, this is a regression from 7.2, the same setup works there. :-( Sorry about this, that's not how we like to release stuff!

**Comment by mov3nforward** [comment] 2020-01-29 15:21
We have checked and double checked the recaptcha settings and they are correct. This is not a user error, but rather a developer error. I am almost positive that we are early adopters of v7.3 because we have submitted multiple complaints to support about the attachment issue over the past 2 weeks. Our client is extremely frustrated that the forms package doesn't work. They have been missing attachments and in our case it has nothing to do with files being named the same. I have tested the form with files from users that tried to submit and they worked for me.

**Forms v7.1.1**
Recaptcha works, but the attachment works sometimes and other times it doesn't. 
There is a button at the bottom of this page called "apply for this position". Click it to show the form.
The form works, but sometimes the attachment is not attached or uploaded. You will notice that the recaptcha works.

https://www.targetpharmasolutions.com/careers/clinical-epidemiologist/


**Forms v7.3**
The recapthca does not work and I am not sure that the attachment issue is fixed.
http://www-dev.targetpharmasolutions.com/careers/full-stack-software-engineer/

The page doesn't have an attachment field and the recaptcha doesn't work.
http://www-dev.targetpharmasolutions.com/contact-us/

This a coding and poor testing issue. Simple things like recaptcha and file attachment should work without question on a paid package. If we had multiple steps with complex questions and attachments, I could see how there may be a problem, but basic things like form fields and attachments, there is not excuse for a paid package not to do the basic features it is advertised to do.

**Comment by nul800sebastiaan** [comment] 2020-01-29 15:38
Thank you, loud an clear! 👍 I'm very sorry that we broke Recaptcha, we're looking into it ASAP. 

Meanwhile, would it be possible for you to test the upload field updates by temporarily removing the Recaptcha field from a form in your development environment. I've not personally been involved in any of the Upload field fixes so I can't say what exactly has been fixed, but I am hopeful it could have helped  in your case.

**Comment by mov3nforward** [comment] 2020-01-31 17:13
Any word on this fix? My client is getting very upset that it’s been over 3 weeks since we reported the issue!!

 

Lee Carroll
 <mailto:leecarroll@forgedmedia.com> leecarroll@forgedmedia.com 

FORGED MEDIA
8313 Six Forks Rd. | Suite 211  |  Raleigh, NC 27615
P: 919-649-0270
 <http://www.forgedmedia.com/> www.forgedmedia.com 

CONFIDENTIALITY NOTICE - The information contained in this message and any accompanying documents may be privileged and confidential and protected from disclosure. If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer. Thank you.

**Comment by bergmania** [comment] 2020-02-03 09:35
PR: https://github.com/umbraco/Forms/pull/320

**Comment by bergmania** [comment] 2020-02-03 10:10
Patch for the ones that cannot wait for 7.3.1 to be released:
[UmbracoForms.Files.7.3.1-ci-20200203-003.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4147284/UmbracoForms.Files.7.3.1-ci-20200203-003.zip)

**Closed** 2020-02-10 12:22 UTC
Labels: release/7.3.1, state/needs-investigation
