### ISSUE TITLE
Submitting a second form fails due to validation when using multiple forms on a page

### ISSUE THREAD

**Issue by highstone** [umbraco/Umbraco.Forms.Issues#449] opened 2020-11-11 13:50 UTC
When using multiple forms on one page, submitting the second form fails after the first form has been submitted succesfully due to the validation failing on the first form. See the screencast below.

The first submitted form is validated when the second form is submit. See the screencast below:

![2020-11-11_14-36-44](https://user-images.githubusercontent.com/7329102/98818915-809f0c00-242c-11eb-8205-e13d0b822d30.gif)

Reproduction
------------
1) Create a simple form with a required field
2) Create a second form with a required field
3) Add both forms to a page
4) Fill in the first form and submit
5) Fill in the second form and submit

Note how the first form validated and the second form does not submit.

Applicable to Umbraco 8.9.0 withUmbraco Forms 8.5.5 - but I believe I have also seen this behavior on Umbraco 7.15.3 with Umbraco Forms 7.3.1.

**Comment by nul800sebastiaan** [comment] 2020-11-17 13:11
Thanks @highstone - I can reproduce this. Turns out before the submit these forms look a bit like this, note the first form's `FormId` property and the second one being different.

![2020-11-17_140746](https://user-images.githubusercontent.com/304656/99394076-9609af80-28de-11eb-8bb8-346289b983e6.png)

After submitting the first form, the second form gets the FormId of the first form! 
Which is very puzzling since the `div` has an id of `umbraco_form_3f1dd7efaea24dd0b5798e8bae0f2260` which is the correct `FormId` (minus the dashes). We'll have to have a look at this. 

![2020-11-17_140837](https://user-images.githubusercontent.com/304656/99394112-a6218f00-28de-11eb-9c93-a24192b84439.png)

**Comment by highstone** [comment] 2020-11-17 16:12
Yup, that's exactly what I noticed, and that's probably what's causing the validation to fail.

**Comment by TimBoonstra** [comment] 2020-11-23 15:20
I had an similar issue, however my 2 forms where exactly the same and on submitting the 2nd form would go trough the workflow of the first form.

I worked around this by modifying the Render.cshtml from:
`@Html.HiddenFor(x => Model.FormId, new {id = (string)null})`
to:
`<input data-val="true" data-val-required="The FormId field is required." name="FormId" type="hidden" value="@Guid.Parse(Model.FormClientId)">`

**Comment by AndyButland** [comment] 2021-10-05 10:58
Will close this one and mark it as fixed in 8.8.0, because as we're now ensuring all form posts - whether to the same page or a new page - do a full "post/redirect/get" cycle, the second form will now not be interfered with by the submitted first form.

**Closed by AndyButland** 2021-10-05 10:58 UTC
Labels: type/bug, state/needs-investigation
