### ISSUE TITLE
File upload overriding when same file name on Umbraco Forms 7

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco.Forms.Issues#445] opened 2020-11-04 18:13 UTC
When a user sends a form with a file with the same name as another previous user, the first file is overriden by the new file uploaded.
When a file is attached to a form using a file upload field, it gets saved to this path: "/media/forms/form_id/field_id/filename.ext"

The problem is we are losing the original file and if an email workflow is executed the link sent is wrong.
This is very serious, as personal info may be sent to the wrong user:
We have a workflow that is sent to the user with the info filled and a link to the documentation uploaded.
This form requires personal documentation.
If the file name is a common name they are overriding and the workflow is sending wrong links, so a user is receiveing personal documentation from another user.

Right now we are solving this issue by creating a workflow that gets executed before and for each file upload value, it renames the file adding a GUID to the filename.
I guess the right solution would be to set this path to "/media/forms/form_id/record_id/field_id/filename.ext" but record_id is 0 when the workflow is executed. May be could it be a GUID...

**Comment by nul800sebastiaan** [comment] 2020-11-10 15:51
Not sure what version you're trying to do this in @teeto but I can't reproduce this at the moment, each attachment seems to be stored in its own unique folder. This is what happens for me on a v7 version, but the test for v8 looks the same. This was a test in both Forms 7.4.1 and Forms 8.5.5.

Did I miss anything?

![forms445](https://user-images.githubusercontent.com/304656/98697159-e4fe9480-2374-11eb-83c8-eb67ab933986.gif)

**Comment by teeto** [comment] 2020-11-11 08:04
I am using 7.1.3, i will update and try again. Thanks @nul800sebastiaan !

**Comment by nul800sebastiaan** [comment] 2020-11-11 08:06
Ah that's a pretty old version! I'll close this for now, It probably was a bug at some point but should be fixed now. 👍

**Closed by nul800sebastiaan** 2020-11-11 08:06 UTC
Labels: state/needs-more-info

**Comment by teeto** [comment] 2020-11-11 10:26
ok, i guess it was solved here on 7.3 https://github.com/umbraco/Umbraco.Forms.Issues/issues/261

**Comment by teeto** [comment] 2020-11-13 16:18
I have updated to 7.4.1 and can confirm this issue is fixed. Thanks!
