### ISSUE TITLE
Question Enable condition is not working

### ISSUE THREAD

**Issue by erictan1024** [umbraco/Umbraco.Forms.Issues#44] opened 2018-11-05 01:55 UTC
I'm trying to setup a question with Enable conditions option checked, to show if another question (prevalue dropdown list) specific item is selected.
The question is not displayed regardless which item I select in the drop down list.

Umbraco version: 7.10.4 assembly: 1.0.6684.15725
Umbraco Forms version: 7.03

To reproduce the issue:
1.	Create a question 
	Answer type: Dropdown
2.	Create another question
	Answer type: Short answer
	Enable conditions: Checked
	Condition: [Show] this field if [all] of the following match:
	    		  [Question A] [contains] [selected value]
Screenshot:
![image](https://user-images.githubusercontent.com/44758902/47973478-95c75e80-e0df-11e8-99a7-cb9dc74b50f1.png)

Screenshot for frontend:
![image](https://user-images.githubusercontent.com/44758902/47973483-a081f380-e0df-11e8-86fb-549e23de58bf.png)

To confirm the issue is not occurred only in my environment, I have created trial cloud account on Umbraco and edited the Contact Us form, and the same issue can be seen there as well.

**Comment by bergmania** [comment] 2018-11-08 12:50
Duplicate of #1 
Duplicate of #24

**Closed by bergmania** 2018-11-08 12:50 UTC
