### ISSUE TITLE
Issue when saving a node when form is added to RTE.

### ISSUE THREAD

**Issue by wonderwilson** [umbraco/Umbraco.Forms.Issues#1139] opened 2023-12-21 14:34 UTC
When saving a node in Umbraco 12 with a form added to the RTE, the following error is displayed: Cannot insert duplicate key row in object 'dbo.umbracoRelation' with unique index 'IX_umbracoRelation_parentChildType'. The duplicate key value is (2267, 2271, 6). The statement has been terminated.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by AndyButland** [comment] 2023-12-30 11:57
I think this is a duplicate of the issue reported [here](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1129) - but with the additional information that the problem arises with the rich text editor as well as the block list.  Fundamentally this is an issue that needs to be solved in the CMS, but there are a couple of workarounds described in the meantime in the linked issue and we'll be picking this up further next week.

**Comment by AndyButland** [comment] 2024-07-10 11:29
Closing this one now as related issues are closed and CMS updates released.

**Closed by AndyButland** 2024-07-10 11:29 UTC
