### ISSUE TITLE
Forms workflowtypes that use the File settingtype throws an exception when submitted

### ISSUE THREAD

**Issue by dangander** [umbraco/Umbraco.Forms.Issues#375] opened 2020-07-16 10:45 UTC
Forms workflowtypes that use the File settingtype throws an exception when submitted - umbracoFile property is undefined.
_.findWhere(item.properties, {alias: "umbracoFile"});

Reproduction
------------

### Bug summary
When using the File settingtype when configuring a workflow (custom or built in), you get an undefined error thrown at line 243 of umbraco.forms.js:
`TypeError: Cannot read property 'value' of undefined`

### Specifics
* Umbraco v8.6.3
* Forms v8.4.1
* Tested in Chrome & new Edge browsers
* Error seems to stem from line 242:
`var umbracoFileProp = _.findWhere(item.properties, {alias: "umbracoFile"});`
item.properties is undefined, so umbracoFileProp doesn't get defined.

### Steps to reproduce

1. Create a form
2. Add a workflow type that uses the file setting (eg "Send xslt transformed email")
3. Select any file
4. Click Select

### Expected result

Configured workflow should be saved with the file selected

### Actual result

Exception thrown in the browser console. Form workflow doesn't get configured.

**Comment by nul800sebastiaan** [comment] 2020-07-20 12:28
Thanks @dangander - I'll close this as a duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/348 and the additional note of it happening with any file setting type is recorded. For now the workaround is to edit the database with the correct file reference (yes, this is very far from ideal).

**Closed** 2020-07-20 12:28 UTC

**Comment by remkovb** [comment] 2020-12-15 15:04
Is there any news about this issue? It's been almost half a year now, but with latest umbraco we still stumble upon this issue... No solution yet?
