### ISSUE TITLE
Dropdown value edited client side can be posted and is accepted as valid, I expect umbraco forms to check if it is a valid value for the dropdown

### ISSUE THREAD

**Issue by stefanbesteman** [umbraco/Umbraco.Forms.Issues#154] opened 2019-04-30 15:04 UTC
A brief description of the issue goes here.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Dropdown value edited client side can be posted and is accepted as valid, I expect umbraco forms to check if it is a valid value for the dropdown

### Specifics

url to test 
https://www.rembrandt-fo.nl/contact/contactformulier/
Search for dropdown 'Ik wil graag meer informatie over'
change value of dropdown item client side and choose the changed dropwdown item. Fill in the rest of the required fields and push submit. Umbraco forms accepts the not valid dropdown value. 

version:
umbraco 7.13.2
umbracoforms 7.1.1
brower: chrome and other

### Expected result
I expect Umbracoforms to return this post as invalid

### Actual result
Post of form with illegal dropwdown value is accepted 

Dennis Aaen (Umbraco Support) had already verified my problem and has reproduced it

**Comment by warrenbuckley** [comment] 2019-05-29 10:02
All merged in @bergmania 💪

**Closed by warrenbuckley** 2019-05-29 10:02 UTC
Labels: release/7.next, release/8.next, state/backlog

**Comment by c9mbundy** [comment] 2019-09-05 22:32
What does this now actually validate?
I've had a problem since 7.1.2 and I'm guessing that it's because option values and/or descriptions set for dropdowns rendered by a custom theme FieldType.DropDownList don't match the item values in Form-Field configuration.
Clearly, if that's the way it now works, then that's not so much a check of client-side tampering, as a simple source-data vs rendered-data comparison.
I need option values and option descriptions to be different - short values, longer descriptions - and was doing it with delimited item values in the form-field config, and parsing that in the fieldType builder.
I can spend time to work around this if the checking is only of the option values against the field's item values, but it's going to be a lot more difficult if the option descriptions (inner-htmlText) also needs to match the item values.
However, if this is being caused by something else I'm not aware of, then I'm going to need to rethink this, so a guide on what is being checked validated would be useful.
