### ISSUE TITLE
Umbraco forms email notification order issue 

### ISSUE THREAD

**Issue by Z3nAg3ncy** [umbraco/Umbraco.Forms.Issues#783] opened 2022-06-09 05:49 UTC
A brief description of the issue goes here.
umbraco form issue 

we have built a large multi page form that when the email notification is sent from the form either using the default template or a plain text email notification does not run in the proper order. 

when we look at in the entries area under the form its in order and when it is exported to excel it is in the right order also. It only seems to when the form is passed to the email notification  

All the other forms on the site work perfectly and arrive through email in the correct order 

we are using umbraco 9.5 and forms 9.4.1

Email order 
![image](https://user-images.githubusercontent.com/30283113/172772843-539a3fe6-4470-4d12-a716-38cc9a4b26f0.png)

Work Flow 
![image](https://user-images.githubusercontent.com/30283113/172773086-b875966e-8ab8-45a4-a737-794d203d0af2.png)

------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by AndyButland** [comment] 2022-06-09 07:28
I think this is effectively a duplicate of [issue 661](https://github.com/umbraco/Umbraco.Forms.Issues/issues/661), so please follow that for a resolution to this issue.

**Closed by AndyButland** 2022-06-09 07:28 UTC
