### ISSUE TITLE
Allow conditionally displayed mandatory fields

### ISSUE THREAD

**Issue by nathanwoulfe** [umbraco/Umbraco.Forms.Issues#40] opened 2018-10-26 06:06 UTC
Would be awesome to be able to have a conditional field also set to mandatory - currently, if a mandatory field is hidden by a condition the form cannot be submitted (as you would expect).

However, there are cases where the required behaviour would be that a conditional field is mandatory - for example, a list of options, where selecting 'Other' displays a conditional fields requesting more information. If that field is not mandatory, the form can be submitted without the user providing more information, which makes the conditional field redundant. 

For example, I might have a radio button list field 'Do you have an enquiry reference number', answering yes to which then displays a text field asking for that number. If it's not mandatory, these fields are pointless as the user could specify that yes they do have said enquiry reference number, but then opt to not provide it.

It could be assumed that a conditional field should always be mandatory, otherwise why ask for the information in the first place...

The desired behaviour would be that changing the visibility of the conditional field also toggles mandatory/optional, with a few different scenarios:

 - optional conditional field is shown -> remains optional
 - optional conditional field is hidden -> remains optional
 - mandatory conditional field is shown -> toggle to mandatory
 - mandatory conditional field is hidden -> toggle to optional

**Comment by bergmania** [comment] 2018-11-08 13:59
Duplicate of #41

I have created a fix for this, such that validation rules are only executed on visible fields on server side, like they are on client by default.

**Closed by bergmania** 2018-11-08 13:59 UTC

**Comment by lukehook** [comment] 2020-07-29 11:48
@bergmania I'm seeing this exact same issue again in Umbraco Forms 8.4.1 - any ideas?
