### ISSUE TITLE
Umbraco forms can extremely slow to load and save

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco.Forms.Issues#1177] opened 2024-02-29 12:19 UTC
It is hard to add details to this issue, as it basically same issue as this one:
https://github.com/umbraco/Umbraco-CMS/issues/14936
and
https://github.com/umbraco/Umbraco-CMS/issues/14842
so it would be worth investigate if maybe same happens in one of umbraco forms services

**Comment by AndyButland** [comment] 2024-03-01 05:53
I don't generally see this as a problem when working with forms in the backoffice... they seem to load and save at reasonable speed for what is needed for backoffice operation.

But please could you share what version you are working with, and perhaps export and attach a form to this issue that you are having trouble with?  We can try to replicate with your setup and see if we see any issues. Thanks.

**Comment by bielu** [comment] 2024-03-03 10:26
Hey,
It happens even on fresh form, so I dont think it is  an issue related to specific of form, I am debugging this futher so I will update findings in next comment

**Comment by bielu** [comment] 2024-03-03 10:38
So I think it is related to some of migrations not running correctly, as I wasn't able to reproduce issue, as we updated our env from v10 to v13, and our table for forms end up with:
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2244074/c4964618-f1e9-4653-a922-5798a7584734)
where locally looks like this:
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2244074/92992747-fa17-4ae0-8ef8-405ad1a739a2)
so I think what we should investigate why it happened.
Upgraded umbraco: 10.7.0 -> 13.2RC
Upgrade umbraco forms: 10.5.1->13.0.1

**Comment by AndyButland** [comment] 2024-05-16 08:18
Closing this one now as seems to be related to specific issue around migrations not being applied.  If we later are able to determine the cause of this more closely we should continue with it in a separate issue.

**Closed by AndyButland** 2024-05-16 08:18 UTC
