### ISSUE TITLE
Unable to delete form entries & rebuild form data

### ISSUE THREAD

**Issue by shahla18** [umbraco/Umbraco.Forms.Issues#228] opened 2019-09-15 05:45 UTC
I am using Umbraco forms 8.1.4 and Umbraco version 8.1.0.

But when I delete the records green bar shows with the message successfully deleted, "Executed Action: Successfully executed action Delete".

However, records still shows in the entries. They are not deleted properly I guess.

No errors are logged. I have even cleared the cache. But entries still doesn't delete even after green bar shows that it has been deleted success fully.

**Scenarios:**

So I have lots of issues with Umbraco forms 8.1.2. Upadted to 8.1.4 , but still issues remains.
Following are the details:
 
I have two forms, **contact us** & **registration**. And I have created custom fields and work flow (See attached code files)
 
But, I am using custom workflow and custom text field only on Registration form.  Contact form is using default fields and workflows of umbraco forms (no custom workflow or fields added to it)
 
**Issues are:** 
**_Issue 1:_** Unable to delete the records from registration form. See errors below from log.
![1](https://user-images.githubusercontent.com/55340800/64917085-15f92e80-d79d-11e9-963d-06b58ea78045.jpg)
![2](https://user-images.githubusercontent.com/55340800/64917086-1a254c00-d79d-11e9-99c3-49da31088ca8.jpg)

**_Issue 2:_** Unable to delete the entries in **Contact us** form. Even if it is a single entry in bulk. It shows success message, but entries remain in the form. Also noticed when manually approved the entries, all fields data was vanished and showing empty. (see screenshot below)
![3](https://user-images.githubusercontent.com/55340800/64917089-375a1a80-d79d-11e9-9e61-a3b899c94563.jpg)

**_Issue 3:_** When tried to rebuild UmbracoFormsRecordsIndex in Examine management , I am getting following error in console & unable to rebuild.
![4](https://user-images.githubusercontent.com/55340800/64917094-4a6cea80-d79d-11e9-9e13-590509fb8eb9.jpg)

Please let me know how can we fix above issue?

Thanks,

---
_This item has been added to our backlog [AB#2691](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2691)_

**Comment by nul800sebastiaan** [comment] 2019-09-16 07:49
Looks like there is unexpected files in the directory where Form uploads are stored, we try to delete files associated to each record and then the directory that is related to the uploaded files. This is not being done in a try-catch block which it probably should be.

**Comment by shahla18** [comment] 2019-09-16 08:18
@nul800sebastiaan what is the path of the directory form file uploads?
U meant to say I should delete App_Data\TEMP\FileUploads and try?

**Comment by nul800sebastiaan** [comment] 2019-09-16 10:00
I meant to say: this is a bug and we need to fix it. 

I don't think I have an intermediate solution for you right now, I am not sure why there's files not being deleted that the code expects to be deleted.

**Comment by shahla18** [comment] 2019-09-22 05:22
@nul800sebastiaan, I need a solution for this please..Can you please provide alternative or temporary solution until fixed in upcoming releases?

**Comment by sebastiandammark** [comment] 2019-09-24 15:23
I'm having the same problem, except that I don't have any form uploads on my form.
My form are pure text inputs.

**Comment by StudioBravo** [comment] 2019-10-09 01:51
We are also having the same issue and our clients are becoming frustrated. When is this fix scheduled for release?

**Comment by shahla18** [comment] 2019-10-09 05:48
@StudioBravo , first two issues has been fixed in new version of umbraco form (8.2.0), however third one related to indexing is still unfixed.

**Comment by StudioBravo** [comment] 2019-10-09 07:04
No Luck @shahla18  we are on version 8.2.0 and Umbraco 8.1.3 
Same error 
ExceptionMessage: "Object reference not set to an instance of an object."

StackTrace: "   at Umbraco.Forms.Core.Services.FieldTypeStorage.GetFieldTypeByField(Field field)
↵   at Umbraco.Forms.Core.Data.Storage.RecordFieldValueStorage.GetRecordFieldValues(RecordField recordFieldInForm)
↵   at Umbraco.Forms.Core.Data.Storage.RecordFieldStorage.GetAllRecordFields(Record record, Form form)
↵   at Umbraco.Forms.Core.Data.Storage.RecordStorage.GetRecords(IEnumerable`1 ids, Form form, Boolean includeFields)
↵   at Umbraco.Forms.Web.Editors.RecordController.PostExecuteRecordSetAction(RecordActionExecution model)
↵   at lambda_method(Closure , Object , Object[] )
↵   at

**Comment by shahla18** [comment] 2019-10-09 07:33
@StudioBravo  Well, I had same issue, but it worked for me when I new created forms or duplicated existing forms (with no previous entries) after updating it to version 8.2.0.  Seems like error remains when you try to delete existing entries even with the new version 8.2.0.

**Comment by bergmania** [comment] 2019-10-11 07:41
Hi Everyone.. 

I have tried to take a look at issue no 3. I have a hard time reproducing it, but I tried to add some more null checks.

Anyone who can reproduce the issue, that would give it a try with this hotfix of 8.2.0?

[UmbracoForms.Files.8.2.0-hotfix.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/3716199/UmbracoForms.Files.8.2.0.2.zip)

**Comment by amfh** [comment] 2019-11-20 13:20
Hi
I have also issue deleting form entries with files uploaded by file upload on the form.

Umbraco 7.15.3
Forms 7.2.0

Unhandled controller exception occurred
System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Umbraco.Core.IO.PhysicalFileSystem.<>c__DisplayClass7_0.<DeleteDirectory>b__0()
   at Umbraco.Core.IO.PhysicalFileSystem.WithRetry(Action action)
   at Umbraco.Core.IO.PhysicalFileSystem.DeleteDirectory(String path, Boolean recursive)
   at Umbraco.Core.IO.PhysicalFileSystem.DeleteDirectory(String path)
   at Umbraco.Core.IO.ShadowWrapper.DeleteDirectory(String path)
   at Umbraco.Forms.Data.Storage.RecordStorage.DeleteRecords(IList`1 allRecords, Form form)
   at Umbraco.Forms.Data.Storage.RecordStorage.DeleteRecord(Record record, Form form)
   at Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(List`1 workflows, RecordEventArgs e)
   at Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(Record record, Form form, FormState state, Boolean editMode)
   at Umbraco.Forms.Web.Services.RecordService.Delete(Record record, Form form)
   at Umbraco.Forms.Web.Providers.RecordActions.Recordsets.DeleteRecordSet.Execute(List`1 records, Form form)
   at Umbraco.Forms.Web.Editors.RecordController.PostExecuteRecordSetAction(RecordActionExecution model)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by Facius** [comment] 2019-11-29 09:26
We also have issues deleting form entries with file uploads: Tried the hotfix @bergmania provided, but with no change. 

We get the follwing error from the api when trying to delete:
![image](https://user-images.githubusercontent.com/318881/69858603-a5898600-1292-11ea-850a-83efc1baab3b.png)

**Comment by jericyuen** [comment] 2020-01-24 10:21
I'm having the same issue but without any upload field, any idea when this will be fixed? The last comment was on end of Nov

I'm on 
Umbraco 8.5.2
Form 8.2.0

**Closed** 2020-01-27 08:08 UTC
Labels: release/8.3.0, state/estimation, type/bug

**Comment by amfh** [comment] 2020-03-06 09:06
Hi
Deleting form entries that contain attachments with the same name causes an error for me. No error deleting entries if all of the attachments has unique name.

Anyone who can help me figure out 
Umbraco 7.15.3
Forms 7.2.0
Unhandled controller exception occurred
System.IO.IOException: The directory is not empty.

**Comment by warrenbuckley** [comment] 2020-03-10 12:25
This has been fixed in this PR here for V7 - https://github.com/umbraco/Forms/pull/330 and will be available in the next version of Umbraco Forms 7.x
