### ISSUE TITLE
8.7.4 Umbraco forms script errors in IE

### ISSUE THREAD

**Issue by Wolfkhan66** [umbraco/Umbraco.Forms.Issues#601] opened 2021-06-25 11:07 UTC
I know IE is going out of support but unfortunately a lot of users out there still use it.

IE is reporting a missing semi colon in this function I assume at the end of the return statement:

    function wrapProviderWithIgnorerBehaviour(provider) {
        return async function(value, element, params) {
                  
             // If field is hidden we ignorer the validation.
            if(element.offsetParent === null) {
                return true;
            }

            return provider(value, element, params);
        }
    }

**Comment by ronaldbarendse** [comment] 2021-06-25 12:26
Thanks for reporting this @Wolfkhan66!

I see this function is located in the `App_Plugins\UmbracoForms\Assets\themes\default\umbracoforms.js` file that's used on the front-end. I don't know about the official browser support for that, only that IE isn't supported for the back-office.

We can add the missing semicolon, but it might also be caused by the `async` function, as that's not supported on IE: https://caniuse.com/async-functions

**Comment by AndyButland** [comment] 2021-06-30 09:45
This has been resolved and will be included in the next release.

**Closed by AndyButland** 2021-06-30 09:45 UTC
