### ISSUE TITLE
Cannot save changes to a record if it contains fields which have been deleted from its form

### ISSUE THREAD

**Issue by ThoughtProcess** [umbraco/Umbraco.Forms.Issues#118] opened 2019-03-18 16:12 UTC
If you have enabled editing form submissions using the `<setting key="AllowEditableFormSubmissions" value="True" />` flag in the UmbracoForms.config file, you cannot save changes to any records that contain field data that no longer exists on the form.

Reproduction
------------

1. Create a form with one or more fields.  For example, "Name" and "Address"
1. Submit the form multiple times, so you have a series of records that contain values for those two fields.
1. Delete the "Address" field.  
1. Save the form.
1. Navigate to the form from the front end using the `?recordId={some_record_guid}` query string feature, so the record will be loaded in edit mode.
1. Make any change to the form and attempt to save it.
1. You will receive an exception stack trace, as shown below:

```
[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Forms.Data.StringHelper.ParseRecordPlaceholders(String value, IRecord record) +195
   Umbraco.Forms.Data.StringHelper.ParsePlaceHolders(HttpContext context, Record record, String value) +74
   Umbraco.Forms.Data.StringHelper.ParsePlaceHolders(Record record, String value) +39
   Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(List`1 workflows, RecordEventArgs e) +454
   Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(Record record, Form form, FormState state, Boolean editMode) +183
   Umbraco.Forms.Web.Services.RecordService.Submit(Record record, Form form) +599
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.SubmitForm(Form form, FormViewModel model, Dictionary`2 state, ControllerContext context) +1592
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.GoForward(Form form, FormViewModel model, Dictionary`2 state) +58
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.HandleForm(FormViewModel model, Boolean captchaIsValid) +440
   lambda_method(Closure , ControllerBase , Object[] ) +143
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
...
```

The problem appears to stem from the `Umbraco.Forms.Data.StringHelper` class, which contains a similar pattern to what I reported in #114:

```
private static string ParseRecordPlaceholders(string value, IRecord record)
    {
      Dictionary<string, string> recordFields = new Dictionary<string, string>();
      if (record.RecordFields != null)
      {
        foreach (RecordField recordField in record.RecordFields.Values)
        {
          string key = XmlHelper.XmlName(recordField.Field.Caption);    // If a field has been deleted from a form, the corresponding RecordField.Field will be null, which means RecordField.Field.Caption will trigger an NPE
          if (recordFields.ContainsKey(key))
            recordFields[key] = recordFields[key] + ", " + recordField.ValuesAsString(true);
          else
            recordFields.Add(key, recordField.ValuesAsString(true));
        }
      }
      ...
```

### Expected result

I should be able to save changes to a record, regardless of how the form might have changed since the record was originally created.  

It's not clear if there's an established convention about what happens to phantom field data in a record--for example, it might be dropped, left alone, etc... ideally it would be great to preserve that data if it accessible in the Back Office, but for now I'd be happy to save edits to records. :)

### Actual result

I get the exception shown above.

**Comment by bergmania** [comment] 2019-03-19 07:50
I'm pretty sure this is fixed by https://github.com/umbraco/Forms/commit/54b3a3a55dd97e2119054b8b9ac6656b08439540?w=1.

The issue was caused because the field returned for the data was null.

The fix is part of the next release.

Duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/114

**Closed by bergmania** 2019-03-19 07:50 UTC

**Comment by agrath** [comment] 2020-04-13 23:43
@nul800sebastiaan @bergmania we're running into the exception above (NRE in ParseRecordPlaceholders) but we are using forms 7.4.0 (the latest v7 version)

I've attached a screenshot of a stack trace from running our repro steps. We have deployed PDBs that we created with Jetbrains from the dll files to get this stack trace in production.

![ParseRecordPlaceholders](https://user-images.githubusercontent.com/78284/79170994-0f22bf00-7e45-11ea-8a11-1cbc413f485e.png)

Can you advise please?

**Comment by agrath** [comment] 2020-04-14 00:10
Just to update a bit more on this, based on the stack trace, we removed the "send email" workflow steps and the crash went away, then we recreated them and the issue didn't reoccur. So maybe some sort of form field state was cached inside the workflow leading to this issue? We're not really sure!
