### ISSUE TITLE
Emails with attachments are not send

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Forms.Issues#486] opened 2021-02-16 11:10 UTC
Emails are not send if you add the attachments with the send email workflow.

To reproduce:
- add a form with a upload
- add a send email workflow
- set attachment to true

If you set attachment to false it sends the emails.

Testen on Umbraco 8.11.1 and forms 8.6.0

**Comment by AndyButland** [comment] 2021-02-16 11:22
Can I ask please if you using a custom media provider @FransdeJong?  I.e. storing your media in Azure blob storage or similar rather than in the `/media/` folder on disk?

If so, think this may be a duplicate of #477.

**Comment by FransdeJong** [comment] 2021-02-16 11:23
Nope, pure umbraco cloud.

**Comment by AndyButland** [comment] 2021-02-16 11:45
OK, thanks, in which case I _think_ that under that hood that will be using an Azure blob storage provider (suggested by [documentation here](https://our.umbraco.com/documentation/Umbraco-Cloud/set-up/Media/Connect-to-Azure-Storage-Explorer/)),  So believe this should be resolved by the fix to #477.

**Comment by FransdeJong** [comment] 2021-02-16 11:47
Great.
Any idea on when that will be released? This month, next month?

**Comment by AndyButland** [comment] 2021-02-16 11:55
I don't, no, but I'll ping @nul800sebastiaan as he may be able to update (and if he and/or you agree, can close this ticket as a duplicate).

**Comment by nul800sebastiaan** [comment] 2021-02-16 13:24
I was thinking the same thing and while forms writes to the media folder, it doesn't by default participate in the blob storage provider as far as I know. A test on U8.11.1 / F8.6.0 turns out to give me a perfectly fine email with attachment, so something else must be going on. Anything in the logs @FransdeJong?

**Comment by nul800sebastiaan** [comment] 2021-02-16 13:25
And here's a screenshot of my email with attachment 
![image](https://user-images.githubusercontent.com/304656/108068704-b9b9ce80-7062-11eb-876b-ed1d72fe5ebe.png)


Also, any specific file type that's being uploaded? Maybe a virus scanner is killing the uploads?

**Comment by FransdeJong** [comment] 2021-02-16 13:31
@nul800sebastiaan 
Thanks for testing!
It looks like you used the "send email with template" workflow?
I'm using the "send email" workflow. Can you please test that workflow to?

**Comment by nul800sebastiaan** [comment] 2021-02-16 13:34
@FransdeJong Ah.. yes that one is broken. And that looks related to the fix Andy is referring to, I'll test that fix as well.

**Comment by nul800sebastiaan** [comment] 2021-02-16 14:56
Had a look: that's exactly what was already fixed as Andy said.

![image](https://user-images.githubusercontent.com/304656/108079640-51bdb500-706f-11eb-8312-5a37bd7a3e53.png)

 I ran a temp build and the two attached dlls are what you can use right now until a new version of Forms is out (I don't have a date yet, but hope it will be soon): [Forms861pre.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/5989469/Forms861pre.zip)

I'll close this as a duplicate of #477!

**Closed by nul800sebastiaan** 2021-02-16 14:56 UTC

**Comment by FransdeJong** [comment] 2021-02-16 15:37
Great!
Than I have one question left.
I know you can't tell me the exact date but when do you expect a release? One, two, three months?

**Comment by nul800sebastiaan** [comment] 2021-02-16 20:19
No no, more like next week or the week after 😅 

I'm just in the process of figuring out what we put in an 8.6.1 patch release and then we'll ship it asap! I think only this one plus an examine indexing bug is what we need for a patch. Then there's some stuff ready for 8.7 but that will be a bit later.
