### ISSUE TITLE
Delete group or field doesn't work

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#384] opened 2020-08-06 14:47 UTC
With latest changes in Umbraco `v8/contrib` branch and Umbraco Forms 8.4.0 I noticed deleting a group or field doesn't seem to work.

![2020-08-06_16-30-16](https://user-images.githubusercontent.com/2919859/89544311-40633880-d802-11ea-90f4-9fe7730e16e3.gif)

It seems to happen because the `umb-confirm-action` component has beeing refactored in https://github.com/umbraco/Umbraco-CMS/pull/8198 and at the moment this has v8.8 as target release.

The current version of Umbraco Forms has the following in

```
<div class="umb-forms__page-actions -fieldset" ng-if="!sortingMode">
    <a href="" ng-click="editFieldset(fieldset)"><i class="icon-settings"></i></a>
    <span>
        <i class="icon-trash" ng-click="togglePrompt(fieldset)"></i>
        <umb-confirm-action ng-if="fieldset.deletePrompt"
                            direction="left"
                            on-confirm="removeFieldset(page, fieldset)"
                            on-cancel="hidePrompt(fieldset)">
        </umb-confirm-action>
    </span>
</div>
```

but not like this in Umbraco core:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html#L103-L111

I think this is because the `show` is false by default and doesn't change:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/components/umb-confirm-action.html#L15

It might be tricky to use the component if the Umbraco Forms version need to support both Umbraco 8.8+ and prior versions.

**Comment by nul800sebastiaan** [comment] 2020-08-11 14:12
Thanks @bjarnef, I've put it on the list of things to look into when we're ready to work on ui/ux issues.

**Comment by nul800sebastiaan** [comment] 2020-08-11 14:15
Interesting, we might need to revert/change a bunch of code in core than as this would probably be a breaking change for other plugins that have this same behavior. Will need to investigate.

**Comment by nul800sebastiaan** [comment] 2020-10-13 13:18
I'll close this as a duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/391 even though you reported earlier! There's some temporary workarounds on there. Thanks again for reporting!

**Closed** 2020-10-13 13:18 UTC
