### ISSUE TITLE
Delete Record...?

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.Forms.Issues#364] opened 2020-06-02 15:44 UTC
Hi!

My main problem is that I want to be able to remove a record from within a Workflow, there's some old examples out there but I have not got any of them to work.

Deleting using IRecordService will throw exception, setting the e.State to Deleted will throw an exception.

I figured I would store the form and record id and then batch delete them in the background later on. But it turns out that its really hard to delete a record...? =D The main problem is that its hard to get an instance of a Record based on the guid id....

Is this possible or should this be kept as a feature request?

**Comment by enkelmedia** [comment] 2020-06-02 16:07
Turns out... that after some digging around there was a IRecordStorage =D 

Using this I could delete a record by kicking of a Task in the background, not the pretties way... but it works. But still.... it would be nice to have a way to flag the record in the "Execute"-method of the workflow....

```

        public override WorkflowExecutionStatus Execute(Record record, RecordEventArgs e)
        {

            Task.Run(() => DeleteRecordWithDelay(record.UniqueId.ToString(),record.Form.ToString()));
            
            return WorkflowExecutionStatus.Completed;

        }

        async Task DeleteRecordWithDelay(string recordId,string formId)
        {

            await Task.Delay(5000);

            try
            {
                IRecordService recordService = DependencyResolver.Current.GetService<IRecordService>();
                IRecordStorage recordStorage = DependencyResolver.Current.GetService<IRecordStorage>();
                IFormService formService = DependencyResolver.Current.GetService<IFormService>();
            
                var form = formService.GetForm(Guid.Parse(formId));
                var record = recordStorage.GetRecordByUniqueId(Guid.Parse(recordId), form);
            
                recordService.Delete(record, form);
            }
            catch (Exception e)
            {

                var exception = e.Message;
                throw;
            }

        }
```

**Comment by nul800sebastiaan** [comment] 2020-06-03 13:57
I'm assuming you're running into this bug? https://github.com/umbraco/Umbraco.Forms.Issues/issues/100

What is it you're trying to do, delete the current record? Or any record? And.. as always: what version are you on please?

**Comment by enkelmedia** [comment] 2020-06-03 17:00
Hi!

Its kind of the same but I'm trying to do this in a custom Workflow by setting record.State to Deleted.

I’m really sorry, we’re on Umbraco 8.6.1 and forms 8.4.1.

**Comment by nul800sebastiaan** [comment] 2020-06-05 09:22
I believe you will get the same or a very similar error as mentioned in issue #100 - seems to be a bug that has been there for quite a while! 🙈 

I'll close this as a duplicate of #100, you can track the progress of that one by subscribing to it.

**Closed by nul800sebastiaan** 2020-06-05 09:22 UTC
Labels: state/needs-more-info
