### ISSUE TITLE
Umbraco Forms - Read Only access

### ISSUE THREAD

**Issue by andrewgrieve-nv** [umbraco/Umbraco.Forms.Issues#240] opened 2019-10-10 20:12 UTC
We are wanting a way to give Read-Only access to the Design of the Form and the Entries, so that our Production Editors cannot change the Design of the Form, but also, that they can see the Entries

Duplicates:

https://our.umbraco.com/forum/umbraco-forms/91428-specific-access-for-users-for-umbraco-forms

**Comment by nul800sebastiaan** [comment] 2019-10-14 09:11
Hey there @left-blank - please note I've moved this issue to the Forms-specific issue tracker.

https://github.com/umbraco/Umbraco.Forms.Issues

For now, we don't have plans to make this a feature in Forms. However, we do offer ways to access the forms entries through APIs that you can use to build an overview. Of course you could also send emails or make other workflows for Forms entries. 

There's documentation available for both v7 and v8 to access the entries: https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Working-With-Data/

**Comment by c9mbundy** [comment] 2019-11-06 05:42
I must admit that I find the 'Forms Security' dialog confusing - although that might be because I've not found any documentation on it. I would have thought that giving access to a form but not giving manage privs, would have resulted in view access for the form, and content-access to the form entries, but apparently not... you need to be able to manage a form to view it or access the entries, which seems counter-intuitive and means there is no obvious way to give an editor access to access the entries for a form without giving them rights to edit the form.

**Comment by AndyButland** [comment] 2022-05-26 10:20
I'll close this one now, as I've realised it's effective a duplicate of #3, which we have now closed following the introduction of this feature in the 8.11/9.3 releases.

**Closed by AndyButland** 2022-05-26 10:20 UTC
Labels: type/feature, status/idea, project/permissions
