### ISSUE TITLE
Custom workflows containing custom settings using TextString or TextField view not working.

### ISSUE THREAD

**Issue by Chris-S-CSS** [umbraco/Umbraco.Forms.Issues#1036] opened 2023-06-19 10:08 UTC
Since upgrading my Umbraco 10 projects to Forms 10.3.3 my custom workflows have stopped working (this also seems to happen in 10.3.2 when I checked). I also reproduced this in a brand new Umbraco 10.5.1 project with Forms 10.3.3

On investigating further it is only those workflows where I have a custom setting using the TextString or TextField view.

In use, when I add one of these workflows to a form the submit button won't close the dialog and a console error appears, for example:

`Possibly unhandled rejection: {"data":{"ExceptionMessage":"Value cannot be null. (Parameter 'key')","ExceptionType":"System.ArgumentNullException, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","StackTrace":"   at System.Collections.Generic.Dictionary``2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)\r\n   at Umbraco.Forms.Web.Editors.WorkflowController.ValidateWorkflowSettings(FormWorkflowWithTypeSettings workflowViewModel)\r\n   at lambda_method6039(Closure , Object , Object[] )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location ---\r\n`

When I rolled back my projects to the version of Forms they had been on previously (10.2.0) my custom workflows began working as expected again.

Reproduction
------------

Create a new Umbraco 10 project and add Forms 10.3.3. Create a custom workflow and add a setting with View = TextField or View = TextString.

Here's an example of mine: 

`[Umbraco.Forms.Core.Attributes.Setting("Start Folder",
            Description = "Id of folder in the media library to add images to.",
            Alias = "startFolder",
            View = "TextField")]
        public string StartFolder { get; set; }`

Run the project and create a new form. Add the custom workflow, populate the custom setting and click Submit.

### Expected result

On clicking Submit the dialog should close and the workflow should be added.

### Actual result

Dialog remains open, console error appears.

---
_This item has been added to our backlog [AB#32303](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32303)_

**Comment by AndyButland** [comment] 2023-06-26 08:47
I'm having trouble replicating this one.

Please could you first check that after the upgrade you have fully cleared the browser cache and Umbraco's cache for any client-side assets (see discussed [here](https://www.andybutland.dev/2022/09/backoffice-cache-busting-with-umbraco.html))?  That will ensure that what's posted from the client-side is as it should be, and ensure there's no mismatch with what's expected on the server-side.

If that's doesn't help, could you share the full code for a custom workflow you have that triggers the issue please?

Also, culd you also let me know what operating system you are using?  Thanks.

**Comment by AndyButland** [comment] 2023-08-05 08:54
I'll close this one now since there's been no further discussion and I wasn't able to replicate the issue at the time of reporting.

**Comment by enkelmedia** [comment] 2023-08-24 14:44
@AndyButland I can reproduce this on v12.0.0.

I have a custom Workflow with one setting:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1782524/0a0efb48-cd64-4bb3-b329-8448d8eed6f4)

This was copied from a v8-site where it used to work, but after comparing my attribute-declaration here with the Umbraco Forms documentation it looks like you never mention the `Alias`-property on the attribute any more. Note here that I'm using the same names as the class-property but in camel-case.

Steping into the source of `WorkflowController.ValidateWorkflowSettings()` shows that the code is looking for a setting with alias `TransactionalEmail` (pascal-case) but my alias was `transactionalEmail`. I think it's some reflection magic that is inconsistent.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1782524/aa976fa5-336e-4fac-96d4-05369fb449e3)

After changing my attribute declaration to pascal case fixes the error.

```
        [Setting("Choose Email",
            Alias = "TransactionalEmail",
            PreValues = "ImPrevalues",
            Description = "I can be description",
            View = "...")]
        public string TransactionalEmail { get; set; }
```
Not entirely sure but it seems like you compare the `Alias` (defined by me) with a `Key` (probably based on the property name on the workflow class) and since the casing is different nothing gets return and we're trying to add null as key for the dictionary.

**Comment by AndyButland** [comment] 2023-08-25 05:52
I see, thanks.  Yes, I can replicate this.  I'm not quite sure of the history behind it, but as you noted, there's some reflection going on to read the settings on the workflow types, and really the "key" used for these settings is the name of the property.  Hence there's not much value in having the alias - if you made it something different to the property name, there would also be issues.  It's - almost but not quite without exception - not used in the out of the box field and workflow types.

At least though, if provided and a different case as is used in your and the OP's example, we should make sure to match it up with a case insensitive check, so we'll do that for the next updates.

**Comment by enkelmedia** [comment] 2023-08-25 06:22
@AndyButland I’m really not sure why I had the alias there, can’t remember for sure but maybe it was to get camel case on the front end.

Seems like mostly a “user error” on my side but would of course be great with case insensitive match or use alias if set. 

If alias is not used maybe consider removing it in upcoming versions - better with breaking change than things not working.

cheers!

**Comment by Chris-S-CSS** [comment] 2023-08-25 09:14
Apologies for the lack of contributing to this thread after starting it, and thanks @enkelmedia for finally getting to the root of the problem.

**Comment by AndyButland** [comment] 2023-09-01 04:33
Will be included in the next round of patch releases.

**Closed by AndyButland** 2023-09-01 04:33 UTC
Labels: type/bug, state/sprint-candidate, release/10.5.1, release/12.1.1
