### ISSUE TITLE
Labels not showing on forms after upgrading to Forms 7.4.1

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco.Forms.Issues#460] opened 2020-11-30 10:46 UTC
On the backoffice we cant see the labels of the form and neither the placeholders

Reproduction
------------
From Umbraco 7.15.6 and Umbraco Forms 7.1.3, update using UmbracoForms.Files.7.4.1.zip and copying all the contents but merging UmbracoForms.config
Following the steps here: https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Installation/ManualUpgrade-v7

### Bug summary

The issue appeared after this updating. If i downgrade to 7.1.3 labels show again.
I do a refresh page and sometimes they load and sometimes not. I have tried clearing the browser cache but it doesnt fix the issue. I am using Chrome but it happens on Firefox too.
Inspecting the label i can see this html:
`<input type="text" class="umb-locked-field__input ng-pristine ng-valid ng-valid-required" name="lockedField" ng-model="ngModel" ng-disabled="locked" ng-class="{'-unlocked': !locked}" placeholder="Alias..." val-regex="^[a-zA-Z]\w.*$" umb-auto-resize="" required="" val-server-field="field_nombre" title="nombre" focus-when="false" umb-select-when="false" on-blur="lock()" disabled="disabled" style="width: 2px;">`

Note the width: 2px, if i change it on the inspector to 40px it shows, so it seems they are hidden on the angular css.

![99779446-5c6eb980-2b15-11eb-9fb6-59588257e9d8](https://user-images.githubusercontent.com/1017314/100600204-432df000-3301-11eb-8154-94bb9606169b.jpg)

If i click on reorder, then i can see the labels:

![99779471-61336d80-2b15-11eb-8b0d-9adcdfd93c4d](https://user-images.githubusercontent.com/1017314/100600233-50e37580-3301-11eb-952c-7f3171faf0ac.jpg)

If i install a clean version of Umbraco with UF v7.1.3 make a form and then update to v7.4.1 the issue does not appear.
Then i have changed connection string to the other project database (the one with the labels problem) and copy App_Plugins/UmbracoForms/Data folder and App_Data/UmbracoForms folder.
I edit the forms and no labels showing again. So my question is, may it be a database issue? maybe the update has to make something to the forms data that it is not done properly? or it has to be updated too?

There is no problem logged on Umbrac log txt and i can see no errors on the console of Chrome inspector.

---
_This item has been added to our backlog [AB#9883](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/9883)_

**Comment by nul800sebastiaan** [comment] 2020-12-09 15:01
You can't "just" change the connectionstring to make Forms work against a different database, if you do that the upgrader doesn't run. In order to get this to work you need to do the same upgrade you did on the local project (copy all the files over and run Umbraco, also make sure to have the same UmbracoForms.config file on both sites).

**Comment by teeto** [comment] 2020-12-15 10:38
Hi @nul800sebastiaan , i guess i did not understand well how it worked.
I have been able to reproduce the problem. This is what i have done:

1. install Umbraco v7.15.6, select SQL CE database version
2. go to forms section, install.
3. create new form, named Test form, it works.
4. reload page, it shows all labels.
5. copy all files inside App_Data\UmbracoForms\Data folder from the problematic project.
6. Inscrease version on ClientDependency.config file.
7. Restart the app and refresh Umbraco Forms section.
8. All the forms appear, some of them get error on opening: "Unable to load form: No provider with id xxxxxx" i think that may have to be with some database provider required on UmbracoForms? anyway, i dont get that error on the problematic project.
9. Try open the Test form created previously, labels are hidden.

I think the problem is with some forms having been created on an older version.
If i delete all the forms from "App_Data\UmbracoForms\Data\forms" folder but the form created with the new version and refresh the application it works again.

If you let me an email i can send you a zip file with the "App_Data\UmbracoForms\Data" contents so you can reproduce it.

**Comment by teeto** [comment] 2020-12-19 10:43
@nul800sebastiaan i need help with this, please could i send you the  "App_Data\UmbracoForms\Data" someway?
Could the problem be that we have lots of forms? we have 136 forms.
We have a licensed umbraco forms but right now are having troubles using it.

**Comment by nul800sebastiaan** [comment] 2021-01-05 11:53
@teeto yes, let's try that! If you can send them to `[sj @ unbraco dot dk]` please then I'll have a look.

**Comment by nul800sebastiaan** [comment] 2021-01-07 15:06
Thanks for sending me the files. It's a weird issue, but somehow the `umb-auto-resize` method is not kicking in (properly). 

There's 2 temporary solutions I can give you:

1. when the form loads, in the top-right click "Reorder" and then click it again, this makes the labels appear again, presumably because the `umb-auto-resize` method gets kicked off properly now
2. in `~\App_Plugins\UmbracoForms\Directives\umb-forms-designer-new.html` you can delete the 3 references to `umb-auto-resize`, after which you need to change the version in ClientDependency.config to refresh the cache - this seems to work in Chrome but I can't vouch for any other browsers

For option 2, the form editor looks a bit uglier but at least it doesn't require extra steps for your editors.

We'll have to work on getting this fixed properly and I unfortunately can't give you a timeline now, but at least we can reproduce this now, thanks!

**Comment by teeto** [comment] 2021-01-08 16:32
OK, i am glad you can reproduce this issue.
We were using the method 1 but i will have a look to method 2 until you fix it.
Thanks.

**Comment by teeto** [comment] 2021-02-08 08:50
Hi @nul800sebastiaan , any updates on the fix?

**Comment by shearer3000** [comment] 2021-02-18 02:59
hello - any update on releasing a fix for this major issue? thanks

**Comment by elit0451** [comment] 2021-03-03 15:38
Thank you for your patience! 🌟 
We have investigated and made a fix for it. While waiting for the next V7 Forms release, here is a zip that you can use to get you back up and running without any workarounds 😉 
[UmbracoForms.Files.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/6077099/UmbracoForms.Files.zip)

**Comment by nul800sebastiaan** [comment] 2021-03-03 16:10
Setting this to fixed for the upcoming v7.5.0.

**Closed by nul800sebastiaan** 2021-03-03 16:10 UTC
Labels: project/backoffice-ux, release/7.5.0, status/regression, type/bug

**Comment by teeto** [comment] 2021-04-15 10:02
i have updated the site to 7.5.0 but i had to change the timeout from 200ms to 1000ms on umbraco.forms.js for it to work fine, some forms still didnt load the labels.
