### ISSUE TITLE
Suggestion: Removal of manual "Install Forms" step after the NuGet installation

### ISSUE THREAD

**Issue by mzajkowski** [umbraco/Umbraco.Forms.Issues#142] opened 2019-04-11 09:35 UTC
If we're installing UmbracoForms NuGet package we shouldn't be forced to click "Install Forms" in the backoffice. The file transformations and new flag items can be delivered together with the NuGet installation which will eliminate manual efforts needed to complete the process.

**Comment by nul800sebastiaan** [comment] 2019-08-06 15:56
Agreed! I can't reproduce this behavior in the latest version though, so I assume it's been fixed by now :-)

**Closed by nul800sebastiaan** 2019-08-06 15:56 UTC

**Comment by bielu** [comment] 2020-06-26 15:03
@nul800sebastiaan I actually can reopen that issue as on 8.6.2 and forms 8.4.1 I have issues with propagating db changes which are correctly propagate with Install of Umbraco Forms.

**Comment by bielu** [comment] 2020-06-26 15:39
Just notice additional thing it is happening only when I will choose empty form!
