### ISSUE TITLE
Forms: 8.5.3 Upgrade Exception - The migration plan does not support migrating from state "1d084819-84ba-4ac7-b152-2c3d167d22bc"

### ISSUE THREAD

**Issue by ahwm** [umbraco/Umbraco.Forms.Issues#401] opened 2020-09-11 21:53 UTC
I upgraded our base site from Umbraco 8.6.3 to 8.70 and also Umbraco Forms 8.5.0 to 8.5.3 and got this message:

> The migration plan does not support migrating from state "1d084819-84ba-4ac7-b152-2c3d167d22bc"

Initial Google Search turned up #387 which helped diagnose the issue. So we had set `StoreUmbracoFormsInDb` to `True` and the upgrade set it back to `False` even though I told it not to overwrite

![image](https://user-images.githubusercontent.com/20478373/92975864-7a011200-f446-11ea-84b6-c12ff1faa578.png)

Setting it back to `True` fixed the problem and I was able to run the application again.

---
_This item has been added to our backlog [AB#8285](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8285)_

**Comment by ronaldbarendse** [comment] 2020-09-15 10:30
As you can see from the comments above the setting, it's not supported to revert this option. Umbraco Forms 8.5.0 and 8.5.1 (incorrectly) used the default `True` value for new installs, instead of `False` for upgrades, hence why the releases were pulled.

Although not supported, you can use the code from my comments on #387 to revert back 👍

**Comment by nul800sebastiaan** [comment] 2020-09-15 11:26
They want the setting to be `True`, as I read it. Upgrading sets it to false again, we need a proper config transform. Right now it's a pretty random "sometimes nuget overwrites the whole config, sometimes it doesn't" scenario, which is very unfortunate.

**Comment by ronaldbarendse** [comment] 2020-09-15 11:40
@nul800sebastiaan Both `UmbracoForms` and `UmbracoForms.Core` NuGet packages don't include config transforms (or build targets that might run transforms). And because the `UmbracoFoms.config` is stored in `\App_Plugins\UmbracoForms`, instead of `\config\`, it's easily overwritten on updates...

**Comment by nul800sebastiaan** [comment] 2020-09-15 11:41
I know, we need to fix that. :-)

**Comment by ahwm** [comment] 2020-09-15 14:10
> They want the setting to be `True`, as I read it. Upgrading sets it to false again, we need a proper config transform. Right now it's a pretty random "sometimes nuget overwrites the whole config, sometimes it doesn't" scenario, which is very unfortunate.

Correct. It had already been set to `True` (and we would like it that way as it simplifies our workflow). and the nuget upgrade reverted it to `False` (against our wishes).

Thanks!

**Comment by nul800sebastiaan** [comment] 2020-10-15 12:18
I've investigated this, when you're upgrading Forms using NuGet in Visual Studio, you get asked if you want to overwrite config files, you need to answer "No" to that. In my testing this did not overwrite the existing settings and everything kept working as it should. I honestly don't know how to produce the scenario where this setting would flip back to `False`. If we have steps to reproduce then I'm happy to re-open this, but for now it seems like not overwriting the config file when asked is sufficient.

**Comment by ronaldbarendse** [comment] 2020-10-15 14:24
@nul800sebastiaan Because Forms also includes a lot of other files that do need to be overwritten (within `App_Plugins\UmbracoForms` and `View\Partials\Forms`), having to manually specify which ones to overwrite or revert afterwards isn't a friendly way to handle upgrades. This is was already the case before this setting, but as it currently throws this migration exception when the config file is reverted to the default, it's something you really need to pay attention to (with _every_ upgrade).

We currently use the following command and revert the config file afterwards:
```powershell
Update-Package UmbracoForms -FileConflictAction OverwriteAll
```

**Comment by nul800sebastiaan** [comment] 2020-10-15 15:27
> `Update-Package UmbracoForms -FileConflictAction OverwriteAll`

😢 NuGet never ceases to make me terribly sad.

**Comment by nul800sebastiaan** [comment] 2020-10-15 15:29
I'm afraid that for the time being we'll have to live with this error popping up sometimes and give upgrade advise. We'll need to re-architect this whole migration to avoid having this problem in the future and I'm not sure where to start at the moment.

**Comment by warrenbuckley** [comment] 2021-03-17 14:43
Fixed in a friendlier error message in this PR - https://github.com/umbraco/Forms/pull/459
Due for release in 8.7.0

**Closed by warrenbuckley** 2021-03-17 14:43 UTC
Labels: release/8.7.0, state/sprint-candidate
