### ISSUE TITLE
Umbraco Forms - Attachments not saved on the server

### ISSUE THREAD

**Issue by galaxylinq** [umbraco/Umbraco.Forms.Issues#504] opened 2021-03-17 14:10 UTC
Umbraco version 7.13.2 assembly: 1.0.6974.19955

Umbraco Forms 7.3.0

1. I can see in the HTTP Post the attachments are being sent, below is a snippet from the raw http post when a form is submitted. (note the names, they are the umbraco ids for the attachments:

-----------------------------428314292411926119951033051576 Content-Disposition: form-data; name="029f9a2e-41fe-4c53-874c-2dc1827f6dfa"; filename="test.txt" Content-Type: text/plain

test -----------------------------428314292411926119951033051576 Content-Disposition: form-data; name="94e4e569-795d-4a05-ba24-5af0fe65d9b1"; filename="test.txt" Content-Type: text/plain

test

2. from the workflow, the attachments fields are empty when i trace print record.ToXml.outerxml: note empty values:
![image](https://user-images.githubusercontent.com/60516543/111481099-026bb280-8709-11eb-9b99-9653bc621e93.png)

3. I don't see any new records under /media/forms either...

What/where could be the problem be?
Thanks,
Ivan S.

**Comment by nul800sebastiaan** [comment] 2021-03-18 16:46
Thanks for reporting @galaxylinq, I've giving this a try but I can't reproduce, this is my experience: 


https://user-images.githubusercontent.com/304656/111663924-8dd06b00-8811-11eb-8d5f-e71c6215c688.mp4

I am using Forms version 7.4.1 though, and it is very well possible that we fixed something around uploads since version 7.3.1. So I would encourage you to upgrade Forms first and try again. If it still doesn't work then we'll need a more detail on how to reproduce the problem since it does work on a clean install as demonstrated above, not sure what's going on for you.

I'll close this for now but please comment here again if you've tried the latest v7 version and you have some more detail on what might be going on, then we can have a closer look 👍

**Closed by nul800sebastiaan** 2021-03-18 16:46 UTC

**Comment by galaxylinq** [comment] 2021-03-31 15:22
Hi, thanks for the comments. What I did is redeploy entire bin folder of my project and that made attachments come through. I am not sure what files were not up to date. This may have been a hosting party issue who is responsibly for pushing the site to production - seems they were pushing some stale contents.

Things seem to work now, except when two files are uploaded, i see this error:
![image](https://user-images.githubusercontent.com/60516543/113168495-b6ddfc00-9212-11eb-938a-cf77c9f7fa25.png)

`
[IOException: The directory is not empty. ]    System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +1091    System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data) +863    System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost) +215    Umbraco.Forms.Core.Providers.FieldTypes.FileUpload.ConvertToRecord(Field field, IEnumerable`1 postedValues, HttpContextBase context) +897    Umbraco.Forms.Web.Controllers.UmbracoFormsController.SubmitForm(Form form, FormViewModel model, Dictionary`2 state, ControllerContext context) +1042    Umbraco.Forms.Web.Controllers.UmbracoFormsController.GoForward(Form form, FormViewModel model, Dictionary`2 state) +91    Umbraco.Forms.Web.Controllers.UmbracoFormsController.HandleForm(FormViewModel model, Boolean captchaIsValid) +442    lambda_method(Closure , ControllerBase , Object[] ) +195    System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +229    System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +35    System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +39    System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +77    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42    System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42    System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38    System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +188    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38    System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +39    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38    System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +43    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +602    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +195    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +128
--

`

do you have any suggestion of why multiple files would be causing this?
