### ISSUE TITLE
Text field is empty if using conditions

### ISSUE THREAD

**Issue by Trobeloo** [umbraco/Umbraco.Forms.Issues#671] opened 2021-11-15 14:28 UTC
A brief description of the issue goes here.

I have a text field/question that is shown depending on a condition from another single choice field. When I process the text field it is always empty. If there is no condition it works.

Reproduction
------------
Create a new form with 2 fields:
Field 1: 
name: "#PR Exchange Environment Label". This the name of a dictionary item.
type: Single choice
Prevalues:
"#PR Office 365 Label". This the name of a dictionary item.
"#PR On Premises Label". This the name of a dictionary item.

Field 2
name:  "#PR Server Count Label". This the name of a dictionary item.
Type: Short answer
Conditions: "#PR Exchange Environment Label" is "#PR On Premises Label".

![2021-11-15_15-24-58](https://user-images.githubusercontent.com/2814461/141798571-fe19bc12-cdc2-4cdc-b7d8-cf4a873a9af6.png)

Run the form then select the "#PR On Premises Label"  choice and enter a value in "#PR Server Count Label". 
Submit the form and see that the value returned is empty.
![2021-11-15_15-26-14](https://user-images.githubusercontent.com/2814461/141798638-cdf4c007-f663-4685-94f3-a49c039ff6f0.png)

Version of Umbraco: 8.17.0
Version of UmbracoForms 8.8.0 (same problem with version 8.9.0-rc001)

**Comment by AndyButland** [comment] 2021-11-16 11:42
Thanks for reporting @Trobeloo - it looks like unfortunately this has been introduced in the 8.8 release, where we resolved [this issue](https://github.com/umbraco/Umbraco.Forms.Issues/issues/292) around the storing of condition values for field entries that aren't visible when the form is submitted.

Previously if a form field was submitted it would be saved, but that meant when a user did something like the following, we'd get entries for fields that weren't visible:

- Choose an option that makes a field visible
- Enter something in that field
- Change the original option so it's no longer visible.

We made a change to process the conditions server side to avoid this problem, so only record values for the visible fields.

We hadn't accounted for dictionary items though - so as in your case, if you have condition based on a value of "#MyKey", the server-side conditions will compare against the literal string "#MyKey" and not the dictionary value that's rendered to the form (and used in the client-side condition logic).

I've got a fix for this in the PR referenced above, and we'll get this out in the next release.  If it's urgent for you or anyone else that comes across this, please let me know and we can consider releasing a patch rather than waiting for the next minor.

**Comment by Trobeloo** [comment] 2021-11-16 11:58
Thanks Andy. Yes having a patch would be great.

**Comment by filefontaine** [comment] 2021-11-19 09:42
Hello @AndyButland ,
We have the 8.8 version on one of your production website.
Can you confirm that the fix will be on the patch 8.9.1 for 23 November 2021 ?
Regards,
Antoine Carette

**Comment by AndyButland** [comment] 2021-11-19 10:28
Yes, that's the version that will contain this fix.

**Closed** 2021-11-19 13:57 UTC
Labels: release/8.9.1, release/9.1.1

**Comment by filefontaine** [comment] 2021-11-23 09:42
Hello, 
i have test the 8.9.1 and for me the problem is not solved.
Here is some of the condition we have :

![image](https://user-images.githubusercontent.com/22192319/143001641-bb7ea108-0cf1-4c6e-8364-4ed6333085ad.png)

If need more details i can send you the forms (i dont know how but i will find)

**Comment by AndyButland** [comment] 2021-11-23 09:46
If you can break it down into a simple test case replicating the problem, please do, and will take a further look.  This specific issue was relating to using dictionary items as condition matches, which it doesn't look like you are using here.  It's possible there's some other case not working as it should that I've missed though.

**Comment by filefontaine** [comment] 2021-11-23 10:14
Ok so i think is because is an old forms 
when i try to recreate the same condition on a other group it works.

**Comment by creativesuspects** [comment] 2021-12-14 19:46
@AndyButland I'm having the same issue after upgrading from Umbraco Forms 8.7.6 to 8.9.1. I'm not using any dictionary items. All the entered values for questions that have a condition or are referenced in a condition on another question are not being saved to the database or included in the email. I fiddled around with the condition settings and it seems the issue may be caused by an 'any' rule, but there aren't any conditions.

So this works:

![image](https://user-images.githubusercontent.com/161342/146067176-08610cfa-e895-4020-b728-550f5ff1e590.png)

But this causes the fields to be empty:

![image](https://user-images.githubusercontent.com/161342/146067293-d130f47f-c010-436c-84ac-f5f78636a95a.png)

Please note that when the 'any' rule is set without any conditions it also breaks when the condition is disabled. So as long as this in the JSON the form breaks:

```json
"condition": {
    "id": "00000000-0000-0000-0000-000000000000",
    "enabled": false,
    "actionType": "Show",
    "logicType": "Any",
    "rules": []
},
```

or

```json
"condition": {
    "id": "00000000-0000-0000-0000-000000000000",
    "enabled": true,
    "actionType": "Show",
    "logicType": "Any",
    "rules": []
},
```

I've included a full copy of the JSON configs for the form I was having trouble with. The issue is caused by the `"logicType": "Any"` on line 100. After changing this to 'All' the form worked again.

[old.json.txt](https://github.com/umbraco/Umbraco.Forms.Issues/files/7714284/old.json.txt)
[new.json.txt](https://github.com/umbraco/Umbraco.Forms.Issues/files/7714283/new.json.txt)

I also encountered some more serious issues with having empty conditions on a form after upgrading to Umbraco Forms 8.9.1. I'm not sure if it's in any way related to what's happening here, but this is the issue I created earlier today:

https://github.com/umbraco/Umbraco.Forms.Issues/issues/686
