### ISSUE TITLE
Cannot read property 'split' of undefined when adding conditions to radio buttons

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#1] opened 2018-09-06 10:35 UTC
First logged as http://issues.umbraco.org/issue/CON-1463

### Steps to reproduce

Using Umbraco 7.6.12 or 7.7.6, and Forms 6.0.5. Also reported in Forms 7.0.2 by Stefan van Leusden.

Create a form with a "Single choice" field with options of "Yes" and "No", followed by a "Short answer" field. Add a condition to the "Short answer" field so that it only shows when the "Single choice" field is set to "Yes".

### Expected result

The short answer field is hidden until "Yes" is selected for the "Single choice" question.

### Actual result

The rule is applied correctly, but there is an error in the Chrome console:

```
 Uncaught TypeError: Cannot read property 'split' of undefined
    at Is (umbracoforms-conditions.js:64)
    at evaluateRuleInstance (umbracoforms-conditions.js:127)
    at evaluateRule (umbracoforms-conditions.js:139)
    at evaluateCondition (umbracoforms-conditions.js:188)
    at evaluateConditionVisibility (umbracoforms-conditions.js:207)
    at isVisible (umbracoforms-conditions.js:215)
    at handleCondition (umbracoforms-conditions.js:221)
    at Object._this.run (umbracoforms-conditions.js:234)
    at Object._this.watch (umbracoforms-conditions.js:110)
    at (index):156
```
### Comment by Patrick Monslaup:

The function that crashes checks if "value" is the same as "expected", and gets a nullpointer on line 64 if the value is null/undefined but expected is not.

At this point you know that the values can't be equal, so add an if sentence before to check if value is undefined but expected is not.   

```
if (value === undefined && expected !== undefined) 
{                
     return false;            
}
```

This makes the method into..        

```
Is: function(value, expected) {
            if ((value \|\| "") === expected) {
                return true;           
            }            
            if (value === undefined && expected !== undefined) {
                return false;           
            } 
            var values = value.split(',');            
            var matchingExpected = $.grep(values,                
                     function(o) {                    
                                    return o === expected;      
                    });            
            return matchingExpected.length > 0;        
}
```

**Comment by bergmania** [comment] 2018-11-08 10:48
Duplicate of #24

**Comment by warrenbuckley** [comment] 2018-11-14 14:45
All tested & good :)

**Closed by warrenbuckley** 2018-11-14 14:45 UTC
Labels: state/review

**Comment by presencewebdesign** [comment] 2018-11-23 14:21
What the hell! So we spent £180 on this and we have to fix the Javascript issues. I am using Umbraco version 7.10.4,

**Comment by obmnbg** [comment] 2019-08-29 06:58
So how's it going to be? Any ideas about the bugfix and when it will come? Right now manually fixing it and hoping next update doesn't overwrite it doesn't really seem to help...

**Comment by attckdog** [comment] 2020-12-09 15:24
In the suggested fix for this, What does this code do?
`            if ((value \|\| "") === expected) {
                return true;           
            }            
`
I'm trying to implement the fix myself but I'm getting unexpected token. I'd rewrite it but I have no idea what it's really doing.
