### ISSUE TITLE
Can't delete field in Umbraco 8.8

### ISSUE THREAD

**Issue by TRES-Internet** [umbraco/Umbraco.Forms.Issues#434] opened 2020-10-22 14:49 UTC
Can't delete a field if added to umbraco 8.8

Reproduction
------------
Install umbraco 8.8 clean & umbraco forms 8.5.1 and try to delete a field on a form.

### Specifics

- Umbraco 8.8
- Forms 8.5.1

### Expected result

I expect to see the checkmark or cancel icon to choose if I want to remove the field

### Actual result
Can't delete the field.

**Comment by nul800sebastiaan** [comment] 2020-10-22 15:15
Thanks, this is a duplicate of #391 - there's a workaround in that issue that can be used until Umbraco 8.8.1 is out. Apologies for the inconvenience!

**Closed by nul800sebastiaan** 2020-10-22 15:15 UTC
