### ISSUE TITLE
Error while adding Umbraco forms to rich text editor

### ISSUE THREAD

**Issue by merinkalapurackal** [umbraco/Umbraco.Forms.Issues#249] opened 2019-11-08 07:43 UTC
A brief description of the issue goes here.

while adding adding umbraco forms to my website i got this error: 'Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'.
But the issue is solved by adding form directly to template.

**Comment by nul800sebastiaan** [comment] 2019-11-08 12:29
Hi @merinkalapurackal, luckily that is not the experience most people have, so there seems to be something wrong for you. Could you be a bit more specific please? Which versions of Umbraco and Forms are you using, what have you tried, has it ever worked, etc.

**Comment by nul800sebastiaan** [comment] 2019-12-05 08:54
I'll close this for now, let us know when you have more details on how to reproduce this issue! 👍

**Closed by nul800sebastiaan** 2019-12-05 08:54 UTC
