### ISSUE TITLE
Forms Validation not working correctly

### ISSUE THREAD

**Issue by LMD8922** [umbraco/Umbraco.Forms.Issues#173] opened 2019-06-06 13:11 UTC
When creating a form in Umbraco backend and using the validation settings such as valid numeric and valid email option, the validation type does not get saved and has no effect when the validation is not met in the front end. On inspecting the input field in the front end, you can see the regex and error message are added as attributes but no validation is performed when trying to submit the form. I am using forms version 8.1.1 and Umbraco version 8.0.1.

Thanks,
Lee

---
_This item has been added to our backlog [AB#8388](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8388)_

**Comment by nul800sebastiaan** [comment] 2019-06-17 07:04
Strange, that should work just fine. Are you sure you've inserted the proper jquery / validator scripts on the frontend?

https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Prepping-Frontend/

**Comment by christopherrobinson** [comment] 2019-06-28 13:44
I'm encountering the same issue as @LMD8922. None of the regular expressions within 'Validation' are persisting in the backoffice, however, when inspecting the raw JSON the expression does exist there.

I have created an example on CodePen of the output from a basic Umbraco Form, and included the required jQuery assets.

https://codepen.io/christopher/pen/ewyWaa

You can see that basic field validation (e.g. is there a value?) is working as expected, but the dedicated email validation is not firing.

**Comment by christopherrobinson** [comment] 2019-06-28 14:06
Okay so I've solved this... instead of `data-regex="@Html.Raw(Model.Regex)"` it should be `data-val-regex-pattern="@Html.Raw(Model.Regex)"`.

**Comment by cdecinkoKnight** [comment] 2019-09-03 15:54
This same issue is happening in Forms 7.1.1.

**Comment by kcharecki** [comment] 2020-02-25 06:17
The problem is that in umbraco.forms.js vm.validationTypes array is initialised AFTER opening the specific form settings. 

Any update when it will be fixed?

**Comment by y0mbo** [comment] 2020-04-07 19:52
Is there any resolution to this issue?
I cannot save a validation regex in the back office with Umbraco Forms 8.3.1.

**Comment by morin0094** [comment] 2020-05-11 12:47
@christopherrobinson Man, thanks! You just saved me a lot of time!!

I can't believe it's isn't been fix since. It's a major issue.

**Comment by warrenbuckley** [comment] 2020-11-24 11:51
Hello all
I have not been able to reproduce this in the following as shown in this GIF

| CMS | Forms
|------|--------
| 8.9.1 | 8.6.0


![forms-bug-173](https://user-images.githubusercontent.com/1389894/100090473-21d58b80-2e4b-11eb-9946-f1685ab7c279.gif)

If anyone can still reproduce this problem in the latest version and can give me some details on how to reproduce this that would be fantastic.

Thanks,
Warren

**Closed** 2020-12-10 09:11 UTC
Labels: project/validation, state/sprint-candidate
