### ISSUE TITLE
Datepicker assets not always being loaded

### ISSUE THREAD

**Issue by BrionyMcKenz** [umbraco/Umbraco.Forms.Issues#694] opened 2022-01-07 13:11 UTC
There is an issue with the assets in the Datepicker.cshtml file not always being loaded.

Reproduction
------------

### Bug summary

The datepicker assets (pikaday js file, moment js file etc) don't get loaded in the DOM if there are multiple forms on the page and the first form doesn't have a datepicker field.
![image](https://user-images.githubusercontent.com/11334470/148548123-0d8c5cbf-7a12-4881-b537-d9fabfe42ffb.png)

### Specifics

Using Umbraco Forms 8.9.0.

### Steps to reproduce

- Create a form **with** a datepicker field
- Create a form **without** a datepicker field
- Add both forms to a page, the one **without** the datepicker field first.

### Expected result

I expect the datepicker assets to be loaded as there is a form on the page with a datepicker field.

### Actual result

The datepicker assets are not loaded and therefore the datepicker field just behaves like a standard text input. 
If I swap the order of the forms around and have the one with the datepicker field first, the assets are loaded.

**Comment by AndyButland** [comment] 2022-01-08 12:25
I think this is a duplicate of [issue 670](https://github.com/umbraco/Umbraco.Forms.Issues/issues/670), which was fixed with the 8.10.0 release.  So since you are on an older version, if you upgrade you should find this is resolved.

**Closed by AndyButland** 2022-01-08 12:25 UTC
