### ISSUE TITLE
Umbraco Forms Index cannot be rebuilt

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco.Forms.Issues#500] opened 2021-03-11 12:58 UTC
Hi!

using Umbraco 8.10.2 and Umbraco Forms 8.6.1. 

With this setting:
`<setting key="StoreUmbracoFormsInDb" value="True" />`

Rebuilding the Umbraco Forms Index runs endlessly ("The process is taking longer than expected, check the umbraco log to see if there have been any errors during this operation") and causes 2 Exceptions:

```
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.
   bei System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   bei System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   bei System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   bei System.Data.SqlClient.SqlDataReader.get_MetaData()
   bei System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   bei System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   bei System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   bei System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   bei StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:Zeile 208.
   bei System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 204.
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 222.
   bei Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:Zeile 172.
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 219.
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 204.
   bei System.Data.Common.DbCommand.ExecuteReader()
   bei NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   bei NPoco.Database.ExecuteDataReader(DbCommand cmd)
ClientConnectionId:a6f806c4-d9c4-499b-8bfd-1b95b901dbe0
Fehlernummer (Error Number):208,Status (State):1,Klasse (Class):16
```
and

```
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.
   bei System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   bei System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   bei System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   bei System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   bei System.Data.SqlClient.SqlDataReader.get_MetaData()
   bei System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   bei System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   bei System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   bei System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   bei System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   bei StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:Zeile 208.
   bei System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 204.
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 222.
   bei Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:Zeile 172.
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 219.
   bei Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:Zeile 204.
   bei System.Data.Common.DbCommand.ExecuteReader()
   bei NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   bei NPoco.Database.ExecuteDataReader(DbCommand cmd)
   bei NPoco.Database.<QueryImp>d__164`1.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei NPoco.Database.Fetch[T](Sql sql)
   bei Umbraco.Forms.Core.Persistence.Repositories.Implement.FormRepository.PerformGetAll(Guid[] ids)
   bei Umbraco.Core.Cache.NoCacheRepositoryCachePolicy`2.GetAll(TId[] ids, Func`2 performGetAll) in D:\a\1\s\src\Umbraco.Core\Cache\NoCacheRepositoryCachePolicy.cs:Zeile 47.
   bei Umbraco.Core.Persistence.Repositories.Implement.RepositoryBase`2.GetMany(TId[] ids) in D:\a\1\s\src\Umbraco.Core\Persistence\Repositories\Implement\RepositoryBaseOfTIdTEntity.cs:Zeile 192.
   bei Umbraco.Forms.Core.Services.BaseService`4.Get()
   bei Umbraco.Forms.Core.Data.RecordIndex.FormsIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   bei Umbraco.Examine.IndexPopulator.Populate(IIndex[] indexes) in D:\a\1\s\src\Umbraco.Examine\IndexPopulator.cs:Zeile 48.
   bei Umbraco.Examine.IndexRebuilder.RebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Examine\IndexRebuilder.cs:Zeile 44.
   bei Umbraco.Web.Editors.ExamineManagementController.PostRebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Web\Editors\ExamineManagementController.cs:Zeile 148.
ClientConnectionId:a6f806c4-d9c4-499b-8bfd-1b95b901dbe0
Fehlernummer (Error Number):208,Status (State):1,Klasse (Class):16
```

Setting the StoreUmbracoFormsInDb to False and rebuilding the index leads to infinite rebuilding process either ("The process is taking longer than expected, check the umbraco log to see if there have been any errors during this operation"), but this time without the above exceptions in logs. 

Suggestions here https://github.com/umbraco/Umbraco.Forms.Issues/issues/454 are not working in our case.

**Comment by nul800sebastiaan** [comment] 2021-03-11 15:14
The fact that you are able to switch from `StoreUmbracoFormsInDb=True` to `StoreUmbracoFormsInDb=False` indicates that something else is wrong first, once forms live in the database you would get an error trying to switch back to forms on disk.

The error indicates the migration to add forms to the database didn't run, the table `UFForms` needs to exists and in the UmbracoKeyValue table you should see the Forms value being `1d084819-84ba-4ac7-b152-2c3d167d22bc` 

![image](https://user-images.githubusercontent.com/304656/110808526-5ba89180-8284-11eb-9e45-3718030be720.png)

After you change `StoreUmbracoFormsInDb` in `UmbracoForms.config` you need to recycle the app pool to make the change take effect. Note: if you set `StoreUmbracoFormsInDb` to `True` you can not go back to `False` immediately, you would then need to delete the `Umbraco.Core.Upgrader.State+UmbracoForms` row from `UmbracoKeyValue` (and I'm not sure if the migration will succeed the second time if the required tables already exist).

However, I can confirm that in either case, a rebuild of the indexes does not complete for me (no errors, just finishes with a message saying `The process is taking longer than expected, check the umbraco log to see if there have been any errors during this operation`).

**Comment by nul800sebastiaan** [comment] 2021-03-11 15:16
Ah.. well, it was because I had no entries, no forms had been submitted. As soon as I have form entries the rebuild completes just fine. So just need to add a small check I guess.

**Comment by nul800sebastiaan** [comment] 2021-03-11 16:20
I've looked into this and it's an examine issue, not a Forms issue, if there's nothing to insert in the index it doesn't return any info and the dashboard will never finish. If you want this fixed I would suggest you raise a PR for it but since it's a rare issue I don't think it's super worth it. 😊 I'll close this as it is not a Forms issue!

**Closed by nul800sebastiaan** 2021-03-11 16:20 UTC
Labels: type/bug
