### ISSUE TITLE
Mandatory field hidden by condition prevent from's submission

### ISSUE THREAD

**Issue by GambitKZ** [umbraco/Umbraco.Forms.Issues#42] opened 2018-10-31 09:39 UTC
If the mandatory empty field was hidden by condition, then it will give an error after you will try to submit the form.

Reproduction
------------

### Bug summary

After we update the Umbraco Forms from v6.0.1 to a newer one (right now it's v6.0.5 but it can be reproduced in any new version) we get many complaints from the customers that forms are not working anymore.
The problem was in the hidden mandatory field which can be skipped in case if user unticks the specific checkbox.
We found a workaround - checkbox should be unticked by default. In this case, the user will not receive an error of the mandatory-hidden field.
Thinking that it's just an error of the v6.0.5 we have tried to update to the latest version (v7.0.4) which gave us the same result. We rolled back to the v6.0.1 and **boom** - it's working again.

A similar description can be found here - https://issues.umbraco.org/issue/CON-1514

### Specifics

v6.0.1 - work as expected
v6.0.5 and above- issue can be reproduced

The tests were done on Chrome and Firefox.

### Steps to reproduce

Create a form with the checkbox which is ticked by default.
Create a mandatory field which will be hidden if the checkbox is unticked.

![image](https://user-images.githubusercontent.com/17333840/47714728-dd756280-dc67-11e8-8163-cff767aeb81b.png)

Open the form on the page. By default, the checkbox is ticked and the field which depends on condition is shown:
![image](https://user-images.githubusercontent.com/17333840/47773719-30592380-dd15-11e8-81d3-a35f3d440a31.png)

Leave the conditional field empty and untick the checkbox and fill the first mandatory field.
![image](https://user-images.githubusercontent.com/17333840/47774053-297ee080-dd16-11e8-8c8c-0a4f462432ef.png)

Click "Submit" which will send the data to the controller, but receive the response with ticked checkbox and error on "should be hidden" field instead of "Thank you" message:
 
![image](https://user-images.githubusercontent.com/17333840/47774293-cf324f80-dd16-11e8-91be-3dbd5f0c20a7.png)

### Expected result

The form should successfully submit the data and show the "Thank you" message.

### Actual result

Instead of the "Thank you" message, the form shows an error on the field which supposed to be hidden and the checkbox which should be unticked is ticked.

**Comment by bergmania** [comment] 2018-11-16 09:05
Duplicate of #40

**Closed** 2018-11-16 09:05 UTC
