### ISSUE TITLE
Can't Delete a Form Feild

### ISSUE THREAD

**Issue by nadiamac** [umbraco/Umbraco.Forms.Issues#391] opened 2020-08-18 20:37 UTC
When you try to delete a Feild from a form, as soon as you check the green tickbox it redirects you directly to your dashboard.

We found a way to get around this, by renaming the form, then it popups the "Page has changed, do you want to discard" message, if you select stay, then it is fine

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
When you try to delete a Field from a form, as soon as you check the green tickbox it redirects you directly to your dashboard.

### Specifics
Initially experienced on Umbraco 8.6.1 - Also Replicated on 8.6.5

Initially experienced on Umbraco Forms 8.3.1 - Also Replicated on 8.5.1

Hosted on Azure with forms files in blob storage using  UmbracoFileSystemProviders.Azure.Forms 

Other Umbraco nuget packages installed
- UmbracoFileSystemProviders 2.0.0
- uSync 8.6.5
- Our.Umbraco.BackOfficeThemes 1.1.0
- Our.Umbraco.Nexu 2.0.1
- Skybrud.Umbraco.Redirects 2.0.4
Replicated on Chrome and Firefox 

### Steps to reproduce
1. Go to the Form Management
2. Select delete , and tick the green tickbox

### Expected result
Field is deleted

### Actual result
Redirects user to the dashboard page

**Comment by nul800sebastiaan** [comment] 2020-08-20 09:26
Hi @nadiamac, unfortunately I can't reproduce this behavior and I do suspect one of your plugins might be causing this. Maybe you can have a look at the browser console when you use the delete button and see what appears there?

**Comment by rbottema** [comment] 2020-08-24 15:18
@nadiamac We also experienced this on Forms 8.2, but could not reproduce on Forms 8.4.2. Looking at the diff, it seems this is due to markup changes in `App_Plugins/UmbracoForms/Directives/umb-forms-designer-new.html` (changing the recycle bin element from an `a` to a `span`). You could try comparing your version of that file with a clean install of the latest Forms to see if there are any changes there?

**Comment by thomassen88** [comment] 2020-10-08 12:30
I got the same issue after upgrading **Umbraco** from 8.7.0 to 8.8.0 and **Umbraco Forms** from 8.4.2 to 8.5.3. The delete-dialog does not appear when i press the delete-button on a field.
See it in action here: https://recordit.co/qVcvAiNSJJ
I have compared the Umbraco-folder and App-plugin folders with a clean version of Umbraco 8.8.0 and Umbraco Forms 8.5.3 and there was no difference.

**Comment by Wolfkhan66** [comment] 2020-10-12 10:53
I have the same issue described by thomassen88.
The confirmation is there but the component doesn't display. It looks like the directive doesn't match the documentation.
https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.directives.directive:umbConfirmAction

**Comment by Wolfkhan66** [comment] 2020-10-12 11:42
Perhaps this change in 8.8.0 is the culprit:
https://github.com/umbraco/Umbraco-CMS/pull/8198

**Comment by Wolfkhan66** [comment] 2020-10-12 11:55
changing the 'ng-if="field.deletePrompt"' to 'show="field.deletePrompt"' in the umb-forms-designer-new.html file fixes the issue. Though the tick and cross are slightly off center on the overlay

**Comment by highstone** [comment] 2020-10-13 10:09
Same issue here. Fresh Umbraco 8.8.0 install with latest and greatest Forms. Create a new form, try to remove a field and the dialog does not show.

Updating the App_Plugins/UmbracoForms/Directives/umb-forms-designer-new.html on line 149 by replacing `ng-if `with `ng-show` does not respolve the issue here @Wolfkhan66

**Comment by nul800sebastiaan** [comment] 2020-10-13 12:23
Argh, that's annoying and a breaking change in CMS I'm afraid! I'll get that reverted.

@highstone - it's `show`, not `ng-show`. Note that in v8.8.1 of CMS we'll revert this so you'll also have to revert the customization in Forms. 

Apologies for breaking it!

**Comment by nul800sebastiaan** [comment] 2020-10-13 14:33
The problematic change has now been reverted and as soon as v8.8.1 is out, the workaround above is no longer necessary. I unfortunately don't have a timeline for the 8.8.1 release yet.

I'll close this for now, thanks again for reporting and digging in deeper!

**Closed by nul800sebastiaan** 2020-10-13 14:33 UTC
Labels: state/needs-more-info, status/regression, type/bug

**Comment by jono-k** [comment] 2020-10-27 19:02
I'm still seeing this issue after upgrading to Umbraco 8.8.1 - is anybody else still seeing it?

**Comment by nul800sebastiaan** [comment] 2020-10-29 17:03
@jono-k Make sure to update the version in your ClientDependency.config (make it 1 higher or lower).
If you have used the previous workaround of changing `ng-if` to `show`, you will need to revert that change as well before changing the ClientDependency version. 

![image](https://user-images.githubusercontent.com/304656/97607265-0e343200-1a11-11eb-8936-a4aaeb5f096b.png)

**Comment by giantpenguin** [comment] 2021-05-23 10:19
I have the issue as @nadiamac on my site with Umbraco 8.12.2 & UmbracoForms 8.2.0.
What should I do?
Thank for your help!

**Comment by giantpenguin** [comment] 2021-05-23 10:47
Have tried to update Umbraco &  UmbracoForms to the latest (8.13.0 & 8.7.3) then facing issue as of @thomassen88.

**Comment by SophieQ608** [comment] 2021-06-01 10:26
Having the same issue as @giantpenguin. We upgraded from Umbraco 8.4.0 to 8.13.0 and Forms from 8.3.1 to 8.7.3. However this is also occurring on our environments that have the 8.13.0 Umbraco version and Forms still at 8.3.1.

**Comment by AndyButland** [comment] 2021-06-01 12:27
Hi @SophieQ608, @giantpenguin - I've had a check again with the latest versions and aren't able to replicate this, but can I check you've tried the suggestion above around updating the version in `ClientDependency.config`.  More details [here](https://adolfi.dev/blog/umbraco-bump-cdf/). That's often needed after upgrades to clear caches.

**Comment by SophieQ608** [comment] 2021-06-01 13:47
Hi @AndyButland - Thank you for getting back to me! I have tried bumping up the CDF version but the issue is still occurring for me unfortunately.
