### ISSUE TITLE
Unable to delete items in forms designer

### ISSUE THREAD

**Issue by thomasddn** [umbraco/Umbraco.Forms.Issues#428] opened 2020-10-15 15:48 UTC
Reproduction
------------

### Bug summary
I'm unable to delete items - such as questions, groups and pages - added to form. Clicking on the bin icon does not show the little popup to confirm the deletion.

### Specifics
Umbraco v8.8.0 (clean install)
Umbraco Forms 8.5.3 (clean install)

### Steps to reproduce

1. Add a new form or edit an existing one
2. Add questions, groups and/or pages
3. [OPTIONAL] Save form
4. Click on the bin icon on the right hand side

### Expected result
The little popup to confirm deletion should show and clicking on the checkmark should delete the item.

### Actual result
Little popup to confirm deletion no where to be seen. As a result, items cannot be removed from the form.

**Comment by nul800sebastiaan** [comment] 2020-10-15 16:17
Thanks, this is a duplicate of #391 - in short: the above workaround can be used until Umbraco 8.8.1 is out. Apologies for the inconvenience!

**Closed by nul800sebastiaan** 2020-10-15 16:17 UTC

**Comment by thomasddn** [comment] 2020-10-16 06:34
Oh, I haven't read that issue through as the OP mentioned something slightly different. But the workaround works!

**Comment by thomasddn** [comment] 2020-10-16 06:48
To re-enable the deletion popup for pages & groups, edit `App_Plugins\UmbracoForms\Directives\umb-forms-designer-new.html` as such:

- pages: replace `ng-if="page.deletePrompt"` with `show="page.deletePrompt"` (line 33)
- group: replace `ng-if="fieldset.deletePrompt"` with `show="fieldset.deletePrompt"` (line 70)

**Comment by nul800sebastiaan** [comment] 2020-10-16 07:13
Please note: when v8.8.1 comes out, you'll have the same problem again, you will need to revert that change in the `umb-forms-designer-new.html` file. Again, sorry for causing this problem.
