### ISSUE TITLE
Fieldmapper from Setting types does not save entered alias and static value

### ISSUE THREAD

**Issue by etharion** [umbraco/Umbraco.Forms.Issues#360] opened 2020-05-26 07:06 UTC
When using the 'Send form to URL' workflow, filling out the fields in the 'Fields' mapper field does not save all information. 'Alias' and 'Static value' appears empty, when you open the workflow after hitting 'Save'. The number of mappings and 'Form value' is saved.

Reproduction
------------

### Specifics
Umbraco: 8.5.5 | 8.6.1
Forms: 8.3.1 | 8.4.1

Before:
![image](https://user-images.githubusercontent.com/15627835/82869971-72693c00-9f2f-11ea-8df7-acb2e07bed19.png)
After:
![image](https://user-images.githubusercontent.com/15627835/82869984-785f1d00-9f2f-11ea-8215-78029ddafd83.png)

### Steps to reproduce
1. Make a form with name, email etc
2. Configure workflow
3. Add new workflow
4. Select 'Send form to URL'
5. Fill out required fields + add 1 or more mappings in the 'Fields' mapper field
 a. When creating mappings, fill out alias and/or static value
6. Hit 'Submit'
7. Open the added workflow
8. Alias and static value data is missing

### Expected result
I expect 'Alias' and 'Static value' to save the information entered in the field after hitting 'Submit'.

### Actual result
It does not save 'Alias' and 'Static value' and entered information is lost after hitting 'Submit'.

**Comment by nul800sebastiaan** [comment] 2020-05-26 08:22
Thanks for the report @etharion. This is a duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/350 which we intend to work on in the next few weeks. For now the workaround is to add a new blank mapping after the last one and then save. 

Apologies for the inconvenience!

I'll close this as a duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/350

**Closed by nul800sebastiaan** 2020-05-26 08:22 UTC
