### ISSUE TITLE
Placeholder parsing problem with Forms 7.4.1

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco.Forms.Issues#362] opened 2020-05-28 09:40 UTC
We are having a problem after upgrading one of our sites to Umbraco Forms 7.4.1 from 7.3.  There is a form with an 'email' field that uses the send email workflow.  In the workflow we use an {Email} placeholder to have the email sent from the submitter's email address.

When the form is submitted the workflow service falls over with a null pointer exception whilst running the record placeholder parsing.  I've tried removing the {Email} placeholder but the error still occurs upon submission.  I've checked the workflow file and have confirmed the placeholder is removed.

I've tested another form that uses the send email workflow, that didn't have any placeholders before the upgrade and I can submit that form absolutely fine.

The stack trace is as follows:

`[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Forms.Data.StringHelper.ParseRecordPlaceholders(String value, IRecord record) +237
   Umbraco.Forms.Data.StringHelper.ParsePlaceHolders(HttpContext context, Record record, String value) +74
   Umbraco.Forms.Data.StringHelper.ParsePlaceHolders(Record record, String value) +39
   Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(List'1 workflows, RecordEventArgs e) +454
   Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(Record record, Form form, FormState state, Boolean editMode) +184
   Umbraco.Forms.Web.Services.RecordService.Submit(Record record, Form form) +605
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.SubmitForm(Form form, FormViewModel model, Dictionary'2 state, ControllerContext context) +1681
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.GoForward(Form form, FormViewModel model, Dictionary'2 state) +58
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.HandleForm(FormViewModel model, Boolean captchaIsValid) +442`

**Comment by nul800sebastiaan** [comment] 2020-05-28 10:22
Thanks @richarth! I can't immediately replicate. I have an email field with a placeholder and an email workflow, this all works. But I don't know what you mean with `{Email}` placeholder? 

Can you provide a very basic sample form that fails for you? I'm interested in the form definition from `~\App_Data\UmbracoForms\Data\forms` and the corresponding workflows definition from `~\App_Data\UmbracoForms\Data\workflows`.

**Comment by richarth** [comment] 2020-05-28 10:47
Thanks for investigating so quickly.  I've created a Gist with the definitions here https://gist.github.com/richarth/88cecf7186f4671f91308379d0d33d14.

If you need anything else please let me know.

**Comment by nul800sebastiaan** [comment] 2020-05-28 12:00
I think this is related to https://github.com/umbraco/Umbraco.Forms.Issues/issues/344

I've attached a build from the fix for #344 which fixes this problem for me, copy the dll files in your bin folder and try it out! I'll close this as a dupe of #344 but do let me know if this helped for you, seems to work with the files you provided! 

[UmbracoForms.Files.7.4.1.Bug362.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4695325/UmbracoForms.Files.7.4.1.Bug362.zip)

**Closed by nul800sebastiaan** 2020-05-28 12:00 UTC
Labels: state/needs-more-info

**Comment by richarth** [comment] 2020-05-29 07:19
This is the same issue we're having .  I've tried the dll files but I'm still getting the error.

**Comment by nul800sebastiaan** [comment] 2020-06-12 09:10
@richarth Sorry, didn't see your reply until now. 

Can I assume you're using NuGet? If you copy the dlls in and then do a build in Visual Studio then NuGet will just replace the dlls again with the old version. Are you absolutely sure the provided dlls have been used?

**Comment by richarth** [comment] 2020-06-15 09:12
No problem, I appreciate the assistance.

We do use NuGet and ran into that problem locally, so I copied the dlls on to our test web server.  I've just recopied the DLLs and retested but am still receiving the same error unfortunately:

`2020-06-15 10:05:35,967 [P4340/D2/T29] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Forms.Data.StringHelper.ParseRecordPlaceholders(String value, IRecord record)
   at Umbraco.Forms.Data.StringHelper.ParsePlaceHolders(HttpContext context, Record record, String value)
   at Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(List'1 workflows, RecordEventArgs e)
   at Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(Record record, Form form, FormState state, Boolean editMode)
   at Umbraco.Forms.Web.Services.RecordService.Submit(Record record, Form form)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.SubmitForm(Form form, FormViewModel model, Dictionary'2 state, ControllerContext context)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.GoForward(Form form, FormViewModel model, Dictionary'2 state)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.HandleForm(FormViewModel model, Boolean captchaIsValid)`

**Comment by nvisage-gf** [comment] 2020-06-18 16:34
Delete the workflow and add it again (worked for one of our forms)

**Comment by richarth** [comment] 2020-07-24 08:57
Thanks @nvisage-gf, I replaced "Attachment": null with "Attachment": "" and the form then worked again.

**Comment by richarth** [comment] 2020-07-24 09:32
After the update to 7.4.2 any properties with a value of null will need the value updating to an empty string ("").  It would be good to get this in the release notes please or get something in place to deal with this or rewrite the values automatically.

**Comment by highstone** [comment] 2020-10-12 07:41
Just ran into this same issue and after a day debugging, wondering and comparing I noticed the same as @nvisage-gf  and @richarth. Replacing `null`'s with `""` did the trick and got the forms working again.

@nul800sebastiaan This should really be accounted for, or at least be clear from the release notes otherwise all existing forms having e-mail workflows will fail.

**Comment by Bmilinski** [comment] 2020-10-14 21:28
I ran into this issue in a staging environment of Umbraco. Luckily it wasn't in production - I suppose the merits of doing things in staging before production. Deleting the workflow, and rebuilding it is what worked for me. Thank you @nvisage-gf  for this resolution! Probably from updating forms all along the way - the site I work on is about 5 years old and has been updated numerous times.
