### ISSUE TITLE
Umbraco forms datepicker not showing calendar

### ISSUE THREAD

**Issue by lisaarman** [umbraco/Umbraco.Forms.Issues#258] opened 2019-12-19 13:20 UTC
When using the date picker in Umbraco forms the dropdown calendar doesn't appear. 

### Specifics

On Umbraco version 8.1.0 and forms version 8.1.3
Using Google Chrime, haven't checked all browsers.

### Steps to reproduce

Rendered a form using formpicker. When there's only one form on the site, the date picker is not working. When another form (same form once again) is added the date picker starts working on the first form, but not the second. When the second form is added agin the datepicker doesn't work.

### Expected result

Expected the datepicker to be shown with only one form on a page.

### Actual result

The datepicker is shown when two forms are on the page, but not a single form. When thereäs only one form it's not working.

---
_This item has been added to our backlog [AB#5511](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5511)_

**Comment by garpunkal** [comment] 2021-02-09 09:20
Any progress on this ?  We're seeing this on a client website. 
![image](https://user-images.githubusercontent.com/13114807/107342334-ff512700-6ab7-11eb-83af-111455c477db.png)

Umbraco 8.11.1
UmbracoForms 8.6.0

**Comment by nul800sebastiaan** [comment] 2021-03-22 09:33
Looks like we forgot to close this one! This has been fixed in 8.6.1 and was caused by a typo in `getElementsById` (should not include an `s`). See: https://github.com/umbraco/Umbraco.Forms.Issues/issues/467

**Closed by nul800sebastiaan** 2021-03-22 09:33 UTC
Labels: project/backoffice-ux, state/sprint-candidate, type/bug
