### ISSUE TITLE
Forms 9+: "DirectoryNotFoundException: Could not find a part of the path 'C:\home\site\wwwroot\umbraco\Data\UmbracoForms\PreValueTextFiles\..."

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Forms.Issues#797] opened 2022-06-30 16:34 UTC
On an Umbraco 9 site with Umbraco Forms: 9.4.1 which I was working on locally, I added a text-file-based PreValue source. It worked perfectly on my local site, but when it was deployed to Azure, the page with that form is returning a server error:

```
An unhandled exception occurred while processing the request.
DirectoryNotFoundException: Could not find a part of the path 'C:\home\site\wwwroot\umbraco\Data\UmbracoForms\PreValueTextFiles\2dc3622e-efa4-4caa-a79c-db6edd73bd8a\us-states-50.txt'.
System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
```

Checking the file system on my local, I see that there is an "Umbraco" folder, which includes "\Data\UmbracoForms\PreValueTextFiles\", but the wwwroot folder does not have that, which might explain why it doesn't get deployed?

Is there some way to have UmbracoForms store its essential files in the wwwroot folder? Or do I need to add a build instruction to copy it over? Or...????

**Comment by hfloyd** [comment] 2022-06-30 17:23
I added a basic post-build event:
`XCOPY /y /E /H /C /I "$(ProjectDir)umbraco\Data\UmbracoForms" "$(ProjectDir)wwwroot\umbraco\Data\UmbracoForms"`

![image](https://user-images.githubusercontent.com/1252593/176739362-eaf71f16-d0cb-4ee9-81a5-c5412476ae00.png)

But I'm not sure if this is the recommended approach?

**Comment by AndyButland** [comment] 2022-07-01 06:27
The default Umbraco `,csproj` file will publish anything in the `/umbraco/` folder apart from anything in the `/umbraco/Data` folder.  And hence exclude your file.

If you add this to your `.csproj` file, then that should ensure it gets included in the publish operation:

```
<ItemGroup>
  <Content Include="umbraco/Data/UmbracoForms/**" CopyToOutputDirectory="Always" />
</ItemGroup>
```

---

Just as an aside, there may be a confusion between `wwwroot` folders; at least I remember scratching my head on an issue around this before.  When you deploy a .NET 5+ app to an Azure Web App, you'll have two `wwwroot` folders.

The first is where your published website is deployed into.
The second is the `wwwroot` folder that's part of the published output, and which you see when developing locally.

E.g. if you go to Kudu, you can see these paths:

```
C:\home>
C:\home\site>
C:\home\site\wwwroot>
C:\home\site\wwwroot\umbraco>
C:\home\site\wwwroot\wwwroot> 
```

So coming back to the issue, Azure is looking for the file in the expected place, but the problem is that the file isn't there after a `dotnet publish` operation.

**Comment by hfloyd** [comment] 2022-07-01 17:01
Thanks, @AndyButland for this info. I'm not doing the deployment on this project (my client is handling the DevOps), but I have added that to the project file and hopefully that will help the next deployment go correctly. 🙂

**Comment by AndyButland** [comment] 2022-07-02 06:15
OK, I'll close this then as I think that will resolve the issue. Obviously please re-open and let me know if not.

**Closed by AndyButland** 2022-07-02 06:15 UTC
