### ISSUE TITLE
Huge memory consumption on UmbracoForms.config string

### ISSUE THREAD

**Issue by techcolin** [umbraco/Umbraco.Forms.Issues#266] opened 2020-01-20 14:37 UTC
We've been trying to pin down memory leak / creep on Umbraco instances running in Azure.  Memory increases slowly over a few weeks until it triggers alerts at over 90%.  After a restart it drops to 50% and starts climbing again.

I downloaded a memory dump for one of the sites today and ran it through JetBrains dotMemory. Iit has highlighted that we have 1.9 million duplicate strings in memory, each containing the path to the UmbracoForms.config file (albeit with a number appended):

![MemDump 2020-01-10](https://user-images.githubusercontent.com/40235909/72734627-039b6100-3b92-11ea-9722-7e68bb448588.png)

`String duplicates inspection

Wasted: 358,539,124
Objects count: 1,907,124
Length: 87
String value:
**D:\home\site\wwwroot\App_plugins\umbracoForms\umbracoForms.config6370188740322208812798`**

This is in Umbraco 7.14.0 running Forms 7.1.1

You can also see in the attached grab above that this memory is also associated with System.Web.FileMonitor

On drilling into this we can see 3.8m dictionary entries for this path:

![FileMonitory 2020-01-20](https://user-images.githubusercontent.com/40235909/72734639-07c77e80-3b92-11ea-8c24-effb087e83e1.png)

Can anyone validate this behaviour, and suggest a fix?

**Comment by techcolin** [comment] 2020-01-24 15:40
Just to provide some further detail  We deployed an update ton Wednesday, which recycled the app pool and returned the memory use to normal.   

We took a memory dump shortly after, then I took another around 24 hours later.  You can see the two outputs here.  One shows no duplicated of the config string, while the other shows 12,802 duplicates have accumulated within 24 hours.  This is most certainly the source of our memory leak - what remains is to understand why. 

We have pinned it down (we think) to the GetFormsSettingFromCache() method in configuration.cs. however we don't fully understand how the GetCacheItem() call would create such a duplicate.

Post recycle:
![MemDump 2020-01-21-POST RECYCLE](https://user-images.githubusercontent.com/40235909/73081533-b71c9200-3ebf-11ea-9423-cd81f26e6390.png)

24 hours after recycle:
![MemDump 2020-01-22-24HOURS](https://user-images.githubusercontent.com/40235909/73081541-bc79dc80-3ebf-11ea-9114-d31fd0221c55.png)

**Comment by techcolin** [comment] 2020-02-06 13:54
Can I respectfully request a progress update or feedback on this?  Or if there's anything we can do to assist?

**Comment by nul800sebastiaan** [comment] 2020-02-06 14:38
Hi @techcolin - of course you may, it looks like I forgot to write anything here, sorry. We need to investigate this and unfortunately it hasn't been prioritized yet. 

I believe the settings are cached until the settings file is changed, which might indeed be where the FileMonitor is coming from. However, it is using the caching from Umbraco Core so it might be that CMS needs to be fixed instead.

**Comment by techcolin** [comment] 2020-02-06 14:47
Thanks - appreciate the update.  Can you post the Umbraco method that is being called as we might be able to do some local testing?

**Comment by nul800sebastiaan** [comment] 2020-02-06 14:56
It lead to IRuntimeCacheProvider.GetCacheItem - probably this implementation: https://github.com/umbraco/Umbraco-CMS/blob/v7/dev/src/Umbraco.Core/Cache/HttpRuntimeCacheProvider.cs#L161

Not sure, might be one of the other implementations of it though.

**Comment by techcolin** [comment] 2020-03-06 17:49
I have tested this thoroughly and found it to be an issue with Umbraco's Cache Extensions, particularly in relation to handling of the cacheDependency path string.  I have raised an issue with more details here:

https://github.com/umbraco/Umbraco-CMS/issues/7773

**Comment by Shazwazza** [comment] 2020-03-26 11:21
I will close this issue since the issue is indeed in the cms.

**Closed by Shazwazza** 2020-03-26 11:21 UTC
Labels: project/performance, state/needs-investigation, type/bug
