### ISSUE TITLE
Form anchoring in Next & Previous buttons

### ISSUE THREAD

**Issue by MMasey** [umbraco/Umbraco.Forms.Issues#1037] opened 2023-06-19 11:46 UTC
At the moment when using the next and previous buttons on a multi-step form, the page doesn't get anchors back to the form.

I have tried this using both the default and a custom form theme.

Reproduction
------------

### Steps to reproduce

1. Create an Umbraco Form with multiple pages
2. Add the form to a page, positioned a fair way down the page to ensure the scrolling is required to view the form
3. Render the form using the default theme (or custom if you have one)
4. Click on the next and previous buttons and the page doesn't anchor back to the form, instead it goes back to the top of the page

Due to how the Umbraco Form functionality works, i'm guessing that it will have to use a similar approach to the "ScrollToFormScript" functionally on successful completion of a form. 

### Specifics

Browser Information - https://whatismybrowser.com/w/GASGBPK
Umbraco Forms Version - 10.3.2

### Expected result

When using the next and previous buttons for multi page umbraco forms, the person should be anchored back to the top of the form.

### Actual result

When using the next and previous buttons for multi page umbraco forms, the person it taken back to the top of the page, loosing focus of the form.

---
_This item has been added to our backlog [AB#30730](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/30730)_

**Comment by AndyButland** [comment] 2023-07-17 04:50
We're prepared this feature now which will be part of the next releases.

**Closed by AndyButland** 2023-07-17 04:50 UTC
Labels: type/feature, state/sprint-candidate, release/10.5.0, release/12.1.0

**Comment by brionymckenzie** [comment] 2023-08-22 13:30
Hi. We're on Umbraco 12.1.1 and Umbraco Forms 12.1.0 and the scroll to form script is working correctly on form submission, but it doesn't work for the next and previous buttons for us. We are using a theme but I have tested using the default theme and it doesn't work there either.

**Comment by AndyButland** [comment] 2023-08-22 13:45
I've re-tested with the latest Forms 12 and it looks to be working as expected.  Could be I'm missing something, or possibly something else on your page is interfering with it, so please you could you try a test with a minimal setup such as what I'm using and see if you see it working (or not)?

I've got a doc type called "Simple Form Page" with just two fields - "Message" (a text field) and "Form" (a form picker).

My minimal template looks like this:

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Forms.Web;
@using Umbraco.Forms.Web.Extensions;
@using Umbraco.Cms.Core.Configuration.Models;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.SimpleFormPage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}
<html>
<head>
<title>Sample Form Page</title>
</head>
<body>
<h1>Sample Form Page</h1>
<p>@Model.Message</p>
<div style="background-color: palegreen; height: 1000px"></div>
@if (Model.Form.HasValue)
{
  @await Component.InvokeAsync("RenderForm", new { formId = Model.Form, theme = "default", includeScripts = true })
}

@Html.RenderUmbracoFormDependencies()

</body>
</html>
```

I've then added a form that has two pages and find as I click the next and previous buttons the scroll position of the form is maintained.

**Comment by brionymckenzie** [comment] 2023-08-22 14:09
Thank you for replying so quick! I just followed your steps above and I'm still having the issue :(

**Comment by AndyButland** [comment] 2023-08-23 07:47
Hmm... then I'm not sure I'm afraid.  I've done another re-test, starting from a clean installation this time, but still I see the expected behaviour of the scroll position being maintained as I navigate between page 1 and 2 of the form.

I'll just replay exactly what I've done and maybe you can spot what differs in your setup that might explain the issue.

Firstly, from Powershell:

```
dotnet new install Umbraco.Templates::12.1.1
dotnet new umbraco -n Forms12Test
cd .\Forms12Test\
dotnet add package Umbraco.Forms
dotnet run
```

Then from the browser:

- Open browser, complete installer providing name, email and password using defaults, sign in.
- Create doc type with template:
	- Name: "Simple Form Page"
	- Single tab: "Content"
	- Single field: "Form" (a form picker)
	- Permissions: Allow at root
- Template contents:

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Forms.Web;
@using Umbraco.Forms.Web.Extensions;
@using Umbraco.Cms.Core.Configuration.Models;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.SimpleFormPage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}
<html>
<head>
<title>Simple Form Page</title>
</head>
<body>
<h1>Simple Form Page</h1>
<div style="background-color: palegreen; height: 1000px"></div>
@if (Model.Form.HasValue)
{
  @await Component.InvokeAsync("RenderForm", new { formId = Model.Form, theme = "default", includeScripts = true })
}
@Html.RenderUmbracoFormDependencies()
</body>
</html>
```

- Create form:
	- Name: "Test Form"
	- 2 pages, each with one "short answer" field
- Create content and select form, save and publish
- View content page and test form navigation between pages

[Exported form](https://github.com/umbraco/Umbraco.Forms.Issues/files/12416570/form-a3380417-3181-4329-8015-3e3e6c02b8a7.zip)

**Comment by brionymckenzie** [comment] 2023-08-23 10:17
Ok, following those instructions works fine so there must be something different about our setup. I will investigate! Thanks for your help!
