### ISSUE TITLE
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.

### ISSUE THREAD

**Issue by afinn-tech** [umbraco/Umbraco.Forms.Issues#454] opened 2020-11-21 13:39 UTC
Since upgrade to 8.5.5 , getting this error on running formsindex in settings examine index
store in db is set to false
Is there any way to clear the error or find which object is valid?
What is stored in this table?
seems related to #411 

thanks

**Comment by nul800sebastiaan** [comment] 2020-11-22 10:01
Thanks @afinn-tech - this has not yet been fixed, please help me understand when you get this error and how it is blocking you?

**Comment by afinn-tech** [comment] 2020-11-22 13:05
@nul800sebastiaan  thanks , i cant run the umbracoformsindex in settings / examine , it shows a 0 files indexed , it fails with this as exception . Not sure if that causes issues  , but i can send the forms ok and they seem to creating the entry . Do you know what the cause is? would changing the store in db to true help?

**Comment by sattapaal** [comment] 2020-11-24 10:50
For what its worth, when you switch from umbraco forms 8.2.1 to umbraco forms 8.5.5, it says that IFormStorage.GetForm() is deprecated, switching to FormService.Get() also gives this error, however, the IFormStorage.GetForm() still works, to get the Json version.

I'd imagine, that a switch for config "Use DB" is probably needed. if use db, use this object, otherwise, get the json form?

**Comment by runegronkjaer** [comment] 2020-11-27 10:33
> For what its worth, when you switch from umbraco forms 8.2.1 to umbraco forms 8.5.5, it says that IFormStorage.GetForm() is deprecated, switching to FormService.Get() also gives this error, however, the IFormStorage.GetForm() still works, to get the Json version.
> 
> I'd imagine, that a switch for config "Use DB" is probably needed. if use db, use this object, otherwise, get the json form?
> 
> edit: just realised this is related to the following:
> 
> #411

I can confirm this. I updated from 8.4.2 and the same problem.

**Comment by afinn-tech** [comment] 2020-12-06 18:40
UFForms table is only created once you add 'store in db is true' , so it looks like it is required no matter , even if store in db is false after the upgrade.

**Comment by sattapaal** [comment] 2021-02-05 15:47
hmm. yes, ive encountered the problem now on indexing, oddly, only older records are not being indexed, but newer ones are.

i wonder if i just create the database table everything might just work.

**Comment by afinn-tech** [comment] 2021-02-05 20:38
@sattapaal  we just cleaned the older records in db , we had a large number of entries , then it allowed the reindex . we have enabled the store in db , then cleaned out old entries so only last 30 days the reindex ran no issues

**Comment by deekoulos** [comment] 2021-02-08 19:13
Hi @nul800sebastiaan!

using Umbraco 8.10.2

When deployments are done to Umbraco Cloud environment, a couple of exceptions are raised which lead to clearing the Indexes (Internal, External and Member) --> All Indexes get empty.

I guess that this is the first exception which is raising and causing the follow up exceptions:
```
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 208
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0()
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
ClientConnectionId:5b1b57b9-153c-4c59-9284-5c3710812bba
Error Number:208,State:1,Class:16
```
Follow up exceptions:
```
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 208
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0()
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.Database.Fetch[T](Sql sql)
   at Umbraco.Forms.Core.Persistence.Repositories.Implement.FormRepository.PerformGetAll(Guid[] ids)
   at Umbraco.Core.Cache.NoCacheRepositoryCachePolicy`2.GetAll(TId[] ids, Func`2 performGetAll)
   at Umbraco.Core.Persistence.Repositories.Implement.RepositoryBase`2.GetMany(TId[] ids)
   at Umbraco.Forms.Core.Services.BaseService`4.Get()
   at Umbraco.Forms.Core.Data.RecordIndex.FormsIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Examine.IndexPopulator.Populate(IIndex[] indexes)
   at Umbraco.Examine.IndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes)
ClientConnectionId:5b1b57b9-153c-4c59-9284-5c3710812bba
Error Number:208,State:1,Class:16
```

```
System.ObjectDisposedException: The collection has been disposed.
Object name: 'BlockingCollection'.
   at System.Collections.Concurrent.BlockingCollection`1.CheckDisposed()
   at Examine.LuceneEngine.Providers.LuceneIndex.QueueIndexOperation(IEnumerable`1 ops)
   at Examine.LuceneEngine.Providers.LuceneIndex.PerformIndexItems(IEnumerable`1 values, Action`1 onComplete)
   at Umbraco.Examine.UmbracoContentIndex.PerformIndexItems(IEnumerable`1 values, Action`1 onComplete)
   at Examine.Providers.BaseIndexProvider.IndexItems(IEnumerable`1 values)
   at Umbraco.Examine.MediaIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Examine.IndexPopulator.Populate(IIndex[] indexes)
   at Umbraco.Examine.IndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes)
```

```
System.ObjectDisposedException: The collection has been disposed.
Object name: 'BlockingCollection'.
   at System.Collections.Concurrent.BlockingCollection`1.CheckDisposed()
   at Examine.LuceneEngine.Providers.LuceneIndex.QueueIndexOperation(IEnumerable`1 ops)
   at Examine.LuceneEngine.Providers.LuceneIndex.PerformIndexItems(IEnumerable`1 values, Action`1 onComplete)
   at Umbraco.Examine.UmbracoContentIndex.PerformIndexItems(IEnumerable`1 values, Action`1 onComplete)
   at Examine.Providers.BaseIndexProvider.IndexItems(IEnumerable`1 values)
   at Umbraco.Examine.ContentIndexPopulator.IndexPublishedContent(Int32 contentParentId, Int32 pageIndex, Int32 pageSize, IReadOnlyList`1 indexes)
   at Umbraco.Examine.ContentIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Examine.IndexPopulator.Populate(IIndex[] indexes)
   at Umbraco.Examine.IndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes)
```

```
System.ObjectDisposedException: The collection has been disposed.
Object name: 'BlockingCollection'.
   at System.Collections.Concurrent.BlockingCollection`1.CheckDisposed()
   at Examine.LuceneEngine.Providers.LuceneIndex.QueueIndexOperation(IEnumerable`1 ops)
   at Examine.LuceneEngine.Providers.LuceneIndex.PerformIndexItems(IEnumerable`1 values, Action`1 onComplete)
   at Umbraco.Examine.UmbracoContentIndex.PerformIndexItems(IEnumerable`1 values, Action`1 onComplete)
   at Examine.Providers.BaseIndexProvider.IndexItems(IEnumerable`1 values)
   at Umbraco.Examine.ContentIndexPopulator.IndexAllContent(Int32 contentParentId, Int32 pageIndex, Int32 pageSize, IReadOnlyList`1 indexes)
   at Umbraco.Examine.ContentIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Examine.IndexPopulator.Populate(IIndex[] indexes)
   at Umbraco.Examine.IndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes)
```

```
System.ObjectDisposedException: The collection has been disposed.
Object name: 'BlockingCollection'.
   at System.Collections.Concurrent.BlockingCollection`1.CheckDisposed()
   at Examine.LuceneEngine.Providers.LuceneIndex.QueueIndexOperation(IEnumerable`1 ops)
   at Examine.LuceneEngine.Providers.LuceneIndex.PerformIndexItems(IEnumerable`1 values, Action`1 onComplete)
   at Examine.Providers.BaseIndexProvider.IndexItems(IEnumerable`1 values)
   at Umbraco.Examine.MemberIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Examine.IndexPopulator.Populate(IIndex[] indexes)
   at Umbraco.Examine.IndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes)
```

This issue seems to related to the UmbracoFormsRecordsIndex. When I try to rebuild this index I get the following exceptions: 
```
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 208
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0()
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.Database.Fetch[T](Sql sql)
   at Umbraco.Forms.Core.Persistence.Repositories.Implement.FormRepository.PerformGetAll(Guid[] ids)
   at Umbraco.Core.Cache.NoCacheRepositoryCachePolicy`2.GetAll(TId[] ids, Func`2 performGetAll)
   at Umbraco.Core.Persistence.Repositories.Implement.RepositoryBase`2.GetMany(TId[] ids)
   at Umbraco.Forms.Core.Services.BaseService`4.Get()
   at Umbraco.Forms.Core.Data.RecordIndex.FormsIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Examine.IndexPopulator.Populate(IIndex[] indexes)
   at Umbraco.Examine.IndexRebuilder.RebuildIndex(String indexName)
   at Umbraco.Web.Editors.ExamineManagementController.PostRebuildIndex(String indexName)
ClientConnectionId:c5b7cf18-4ca8-4ad2-875d-6e0e1e8af52b
Error Number:208,State:1,Class:16
```

```
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 208
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0()
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.Database.Fetch[T](Sql sql)
   at Umbraco.Forms.Core.Persistence.Repositories.Implement.FormRepository.PerformGetAll(Guid[] ids)
   at Umbraco.Core.Cache.NoCacheRepositoryCachePolicy`2.GetAll(TId[] ids, Func`2 performGetAll)
   at Umbraco.Core.Persistence.Repositories.Implement.RepositoryBase`2.GetMany(TId[] ids)
   at Umbraco.Forms.Core.Services.BaseService`4.Get()
   at Umbraco.Forms.Core.Data.RecordIndex.FormsIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Examine.IndexPopulator.Populate(IIndex[] indexes)
   at Umbraco.Examine.IndexRebuilder.RebuildIndex(String indexName)
   at Umbraco.Web.Editors.ExamineManagementController.PostRebuildIndex(String indexName)
ClientConnectionId:c5b7cf18-4ca8-4ad2-875d-6e0e1e8af52b
Error Number:208,State:1,Class:16
```

Best
Dee

**Comment by sattapaal** [comment] 2021-02-09 13:04
> @sattapaal we just cleaned the older records in db , we had a large number of entries , then it allowed the reindex . we have enabled the store in db , then cleaned out old entries so only last 30 days the reindex ran no issues

this wont work for our case, we need the old records to show the draft "partially submitted" forms.

this is an big issue. i wonder if there is a way to manually execute the indexing without the need to "store umbraco forms in database". because not everyone will be storing forms in the database after an upgrade, unless its a forced requirement for us to do so?

if we are forced to do so, we need to know the implications of doing so too. it still feels like we're not checking for "is stored in database" config isnt being checked. **if** is stored in database, check UFForms table for form, **else,** use the old JSON form storage? 

obviously i'm over-simplifying it :D

**Comment by nvisage-gf** [comment] 2021-02-16 14:45
This issue causes Content Deploy (full / partial restore) to fail in Umbraco 8.11.1, Forms 8.6.0 and Deploy 3.5.3; our system form schema stored via AzureBlobFileSystem.ContainerName:forms

**Comment by sattapaal** [comment] 2021-02-16 16:26
from what we know, we have to turn on store forms in DB for it to work.

but we just dont know what the impact of it is. i may turn this on in a separate app, see what happens.

**Comment by jemayn** [comment] 2021-03-09 15:09
Just ran into this as well. @nul800sebastiaan do you need any reproduction steps or more info about anything? 🙂

As far as I can see it happens on any fresh setup not enabling storage in the db (which is off by default even on new installs). Not immediately noticeable as the index seems to not be used in the backoffice. However when trying to use fx the methods on this page it relies on the index and returns empty results: 
https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Working-With-Data/#getapprovedrecordsfromform

**Comment by AndyButland** [comment] 2021-03-09 15:45
@nul800sebastiaan - it looks like this was fixed in [this PR](https://github.com/umbraco/Forms/pull/402) in December, but perhaps hasn't been released yet.  If you agree, think we can mark this as closed and due in 8.7.0.  It certainly looks like the fix applied there would resolve this issue from the stack trace posted above.

**Comment by nul800sebastiaan** [comment] 2021-03-10 07:26
That PR was a fix for https://github.com/umbraco/Umbraco.Forms.Issues/issues/411 which is included in v8.6.1, so the question is: did it accidentally also fix this one? Not sure! What version are you on @jemayn?

**Comment by AndyButland** [comment] 2021-03-10 08:00
Great, good to hear.  I'll close this issue then and label it with the right release so it doesn't cause confusion in the future.

**Closed by AndyButland** 2021-03-10 08:00 UTC
Labels: release/8.6.1, state/needs-more-info

**Comment by skartknet** [comment] 2021-04-16 04:37
I'm having this issue. I have StoreUmbracoFormsInDb = false. I'm using Umbraco 8.12.2 and Umbraco Forms 8.7.1. This is my code:

    public class ExportAllFiles : SaveAllUploadedFiles
    {
        private readonly IFormService formService;

        public ExportAllFiles(IFormService formService)
        {
            this.formService = formService;
        }

        public override string ExportToFile(RecordExportFilter filter, string filepath)
        {                      
            var form = formService.Get(filter.Form);            //failing here

            return "";
        }
    }

**Comment by AndyButland** [comment] 2021-04-16 06:00
Hi @skartknet  - the issue here looks to be that you are not storing forms in the database, but are looking to to use the `IFormService` which is expecting the database tables to exist.

You need to look at using `IFormStorage` I believe.  This is the older method of accessing form data (and will use the "forms on disk" method, or delegate to the "forms in database" via `IFormService` if enabled).

Just to note this kind of confusion and simplification is something we're considering streamlining to only support "forms in database" in V9... see discussion [here ](https://github.com/umbraco/Umbraco.Forms.Issues/issues/540)if you have any views on that.

**Comment by skartknet** [comment] 2021-04-20 03:36
Thanks @AndyButland , yes using `IFormStorage `worked.

**Comment by RunnicFusion** [comment] 2023-01-12 07:57
Thanks @AndyButland for the heads-up! :)
