### ISSUE TITLE
Cannot delete either fiels, nor fieldset nor page in Umbraco 8.8

### ISSUE THREAD

**Issue by doronuziel71** [umbraco/Umbraco.Forms.Issues#437] opened 2020-10-25 13:11 UTC
I am not sure whether this is a bug for FORMs or UmbracoCMS - but it seems that in newest umbraco version - 8.8 to date - they don't play along well.

For us it a **HUGE** issue, We are seconds from handing a new project to a client. The project relies on **Forms** and **Content Blocks** - so we need the two to play along.... We have a purchased license - if this is an issue here.

Reproduction
------------

### Steps to reproduce

Go to the Forms section of an Umbraco 8.8 installation.
Select an existing Form Definition
Try to delete an existing field,

### Expected result

A confirm widget should show up and if green mark is selected -field will be deleted.
### Actual result

The confirm small widget next to the delete button doesnt show. 

From a very brief investigation it seems that in current umbraco version the **umb-confirm-action** directive expects a **show** param, where in previous versions it relied on **ng-if**.
Umbraco Forms still seems to be using ng-if (see: **umb.form-designer-new.html**).
I am not 100% sure that this is the reason -I tried to change the above file manually, but I am probably missing something as it doesnt take..... 
If this bug cannot be solved quickly - I would appreciate if at least I am advised on how to resolve this locally.

**Comment by doronuziel71** [comment] 2020-10-25 13:31
Just to soften the blow - after a really hard cache refresh for my browser I was able to change "umb-form-designer-new.html" and replace **ng-if** with **show** for all the occurances of **umb-confirm-action** directive.
I can confirm that the above action resloves the issue.

**Comment by nul800sebastiaan** [comment] 2020-10-27 08:31
Thanks, this is a duplicate of #391 - there's a workaround in that issue, which is the same that you found. Umbraco 8.8.1 is out today which will fix this problem. Apologies for the inconvenience!

**Closed by nul800sebastiaan** 2020-10-27 08:31 UTC

**Comment by doronuziel71** [comment] 2020-10-28 12:49
Thank you @nul800sebastiaan

**Comment by Flopi04LP** [comment] 2022-08-10 13:56
Just had a smiliar issue in Umbraco 10, the solution was also to delete the browser cache.
