### ISSUE TITLE
Google Recaptcha Follow up

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Forms.Issues#458] opened 2020-11-26 06:46 UTC
After a Call with a google team member and a different platform form with recaptcha v2 being bypassed there is a Russian tool and bot going through AWS hitting sites and bypassing forms.
If you not been hit, you are likely soon.

The google support rep said they know of it. There is a fix to one bot in code:

var error = field.Settings["ErrorMessage"];

A solution provided to was along the lines of:
var error = (field.Settings.ContainsKey("ErrorMessage")) ? field.Settings["ErrorMessage"] : string.Empty;

A blog post is incoming on the matter but they are recommended moving to ReCaptcha V3. So in that, if the code above will not help I ask if this can be updated as soon as possible for Umbraco forms. You will see this being a commonly raised problem in the next few months in the community.

_Originally posted by @nul800sebastiaan in https://github.com/umbraco/Umbraco.Forms.Issues/issues/446#issuecomment-724833350_

**Comment by nul800sebastiaan** [comment] 2020-11-26 08:38
@thenexus00 For now you can use https://our.umbraco.com/packages/website-utilities/recaptcha-v3-for-umbraco-forms/

**Comment by c9mbundy** [comment] 2020-11-26 09:50
@nul800sebastiaan Unfortunately that leaves V7 sites exposed.

**Comment by thenexus00** [comment] 2020-11-30 00:33
> @nul800sebastiaan Unfortunately that leaves V7 sites exposed.

This is my next question - what we do about the version 7 ones, what options do we have?
This is actually something on going as starting to see this hit the web now with more and more people seeing a massive spam spike.

**Comment by thenexus00** [comment] 2020-11-30 04:11
> @nul800sebastiaan Unfortunately that leaves V7 sites exposed.

The plugin link said it was tested with later versions of 7 but it does not install so I reached out to see if those versions can be made available at least in the archive tab.

**Comment by c9mbundy** [comment] 2020-12-03 00:17
@thenexus00 Actually, I don't think that's quite the way the compatibility ratings work. They are community reports of experience using a package, not the developer claiming compatibility. The ratings are subject to errors and misreporting, and so should be taken with a large grain of salt.

**Comment by MichaelNielsenDK** [comment] 2020-12-07 10:25
We're seeing the same issue on sites on Umbraco Cloud, so it's not limited to just AWS hosting. 

Can't we get a patch for this, so we do not have to rely on a third party package that may or may not work on v7 sites?

**Comment by c9mbundy** [comment] 2020-12-07 21:57
Our Umbraco-Cloud sites are likewise taking a hammering from this, and being v7 sites they can't use the package referred to.
The package referred to won't work for Umbraco-Forms-7 - the community reports are wrong - as the code is clearly v8 only.

**Comment by thenexus00** [comment] 2020-12-08 04:15
Other CMS solutions such as Kentico are also getting a massive influx at the moment so it is clearly a flaw now easily bypassed in reCaptcha v2 so I think efforts to have V3 officially in and a solution for everyone on V7 seems really important.

**Comment by nul800sebastiaan** [comment] 2021-01-06 16:23
I'll close this as a duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/455 - I've added some more info there.

**Closed by nul800sebastiaan** 2021-01-06 16:23 UTC

**Comment by nul800sebastiaan** [comment] 2021-01-06 16:25
@thenexus00 The code you're looking for is already as suggested:

```csharp
                var error = field.Settings.ContainsKey("ErrorMessage") 
                    ? field.Settings["ErrorMessage"] 
                    : "Make sure to complete the \"I am not a robot\" challenge";
```
