### ISSUE TITLE
Umbraco forms UI issue for validation

### ISSUE THREAD

**Issue by AndreyKarandashovUKAD** [umbraco/Umbraco.Forms.Issues#274] opened 2020-01-31 09:52 UTC
### Steps to reproduce:

1) Create a form with a short answer field.
2) Go to the “Validation” section and select “... or enter a custom validation”.
3) Use any regular expression and error message. http://prntscr.com/qvi3x4
3) Click submit
4) Open the settings again and check the verification section.
5) The validation is empty, but the message exists http://prntscr.com/qvi4o4

### Expected result:

I see the selected validation type and regular expression for the field.

### Actual result:

I don't see validation settings except for message.

**Umbraco forms version is 8.2.0**
**Umbraco version is 8.2.2**
I also can reproduce it with Umbraco 8.5.3

By the way, everything works fine on the site, but I can’t check which regular expression I use for a specific field.

---
_This item has been added to our backlog [AB#5506](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5506)_

**Comment by nul800sebastiaan** [comment] 2020-01-31 12:12
Oh that's indeed quite unfortunate, I can reproduce this. ✔️

**Comment by nul800sebastiaan** [comment] 2020-03-03 13:05
I believe this is essentially the same issue as #276 - need to test

**Comment by simoneldevig** [comment] 2020-03-25 09:22
I'm having this issues as well in forms 8.3.2 on Umbraco 8.4.0 :-)

**Comment by rly-nozebra** [comment] 2020-03-25 10:23
Am I correct, that a fix is planned for release 8.4.0? When can we expect 8.4.0 to be ready?
And isn't this enough for a minor fix version?

**Comment by nul800sebastiaan** [comment] 2020-03-25 11:03
@rly-nozebra 8.4.0 is due out next week. We have larger items ready for 8.4.0 as well, so it will be part of a new minor release.

**Comment by rly-nozebra** [comment] 2020-03-25 11:13
@nul800sebastiaan Thank you for the reply

**Comment by nul800sebastiaan** [comment] 2020-04-23 08:54
Oops, looks like I forgot to close this one. This is indeed fixed in 8.4.0, but we have some other problems with 8.4.0 and I would advise you wait until 8.4.1 is available next week to upgrade. 

The issues fixed in 8.4.1 are listed here: https://github.com/umbraco/Umbraco.Forms.Issues/issues?q=label%3Arelease%2F8.4.1+ 

If you need this fixes now, then a build with all the fixes applied is available now: 
[UmbracoForms.Files.8.4.1-alpha.20200423.6.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4521345/UmbracoForms.Files.8.4.1-alpha.20200423.6.zip)

**Closed by nul800sebastiaan** 2020-04-23 08:54 UTC
Labels: project/backoffice-ux, release/8.4.0, state/sprint-candidate, type/bug
