### ISSUE TITLE
Error - The SessionStateTempDataProvider class requires session state to be enabled

### ISSUE THREAD

**Issue by c9mb** [umbraco/Umbraco.Forms.Issues#743] opened 2022-03-10 22:01 UTC
UF-7.5.7 with Umbraco 7.15.7 - hosted on Umbraco-Cloud.

I am regularly encountering the error listed below on multiple sites, and support has indicated that this is likely coming from Umbraco-Forms.

The error message itself provides precious little detail as to the the originating cause, so UF is more an intuitive guess at this point.

SessionState mode is not disabled on any of the sites, and this is only happening on some of my v7 sites, but all of them are running exactly the same code-base (via Baseline deployment) and are using the same configuration - so it's hard to work out why some and not others.

So far, the only thing in common with those logging this error, is that they are the ones with a bigger SEO/SERP presence, and are attracting far more spam-bot form submission attempts.

All sites are using reCAPTCHA v3 to protect the forms, but I can't yet see how it's possible to submit a form without the SessionState being enabled for the request.

```
ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.InvalidOperationException: The SessionStateTempDataProvider class requires session state to be enabled.
at System.Web.Mvc.SessionStateTempDataProvider.SaveTempData(ControllerContext controllerContext, IDictionary`2 values)
at System.Web.Mvc.Controller.PossiblySaveTempData()
at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by AndyButland** [comment] 2023-03-01 09:12
I'm afraid we are no longer working on Forms 7 other than dealing with any security related issues, following the [Umbraco 7 end of life schedule](https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/umbraco-7-end-of-life-eol/) (which took this version into the security-only phase from July 2021).  Hence at this stage we'll close this issue.

Of course if the problem is found on a later version, please feel free to open a new issue indicating the versions affected.

**Closed by AndyButland** 2023-03-01 09:12 UTC
