### ISSUE TITLE
Send template email - Include sensitive data resets to false after refresh

### ISSUE THREAD

**Issue by robjakedorsett** [umbraco/Umbraco.Forms.Issues#819] opened 2022-07-14 16:34 UTC
Hi, 
I'm having an issue with the send email template workflow "Include Sensitive Data" checkbox.  It doesn't seem to be persisting when refreshing the page.
Versions:
Umbraco Forms: 9.3.0
Umbraco version 9.5.0

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Include sensitive data, checkbox doesn't persist upon page refresh, despite saving in the CMS.

### Steps to reproduce

1. Go to the forms section
2. Go into a form
3. Add "Send email with template (Razor)" workflow
4. Enable "Include Sensitive data toggle
5. Click "Submit"
6. Click "Save"
7. Refresh the back office
8. Click into the workflow created in step 3

### Expected result

The toggle should be persisted (be enabled)

### Actual result

The toggle is disabled

**Comment by AndyButland** [comment] 2022-07-15 05:02
This looks like a duplicate of #780, which has now been resolved if you are able to upgrade to 9.4.2.

**Closed by AndyButland** 2022-07-15 05:02 UTC

**Comment by robjakedorsett** [comment] 2022-07-15 08:26
Ah - Thank you @AndyButland
