### ISSUE TITLE
Unable to delete questions

### ISSUE THREAD

**Issue by AcidNoX** [umbraco/Umbraco.Forms.Issues#432] opened 2020-10-21 11:19 UTC
**Nuget versions:**
Umbraco 8.8.0
UmbracoForms 8.5.3

**Browsers Tried:**
Chrome: 86.0.4240.75 (Official Build) (64-bit)
Firefox: 81.0.1 (64-bit)

When clicking on the trash can icon on a question, the tick and cross buttons to confirm the action do not appear making it impossible to remove a question from a form.

This happens on existing forms and newly created forms. For example: I'm unable to remove the default data consent question that is added.

![image](https://user-images.githubusercontent.com/8410021/96712775-88bcdc00-1397-11eb-9ec6-0115857c165d.png)

**Comment by nul800sebastiaan** [comment] 2020-10-21 11:33
Thanks, this is a duplicate of #391 - there's a workaround in that issue that can be used until Umbraco 8.8.1 is out. Apologies for the inconvenience!

**Closed by nul800sebastiaan** 2020-10-21 11:33 UTC

**Comment by AcidNoX** [comment] 2020-10-21 11:39
No worries, thanks for getting back so quickly! :)
