### ISSUE TITLE
Problem with client side validation of mandatory RadioButtonList and CheckBoxList fields

### ISSUE THREAD

**Issue by SteveVaneeckhout** [umbraco/Umbraco.Forms.Issues#157] opened 2019-05-02 12:54 UTC
Copied from [https://issues.umbraco.org/issue/CON-438](https://issues.umbraco.org/issue/CON-438)

### Bug summary

Clientside validation of a RadioButtonList or CheckBoxList doesn't work.

### Specifics

Umbraco Forms 7.1.1 and older

### Steps to reproduce

- Create a form with a RadioButtonList or CheckBoxList field.
- Set the field as mandatory.
- Notice the client side validation does not work when submitting the form when no choice has been made.

### Solution
- `\Views\Partials\Forms\Themes\default\Fieldtypes\FieldType.RadioButtonList.cshtml`
Line 10 change `data-val-requiredlist` to `data-val-required`
- `\Views\Partials\Forms\Themes\bootstrap3-horizontal\Fieldtypes\FieldType.RadioButtonList.cshtml`
Line 18 change `data-val-requiredlist` to `data-val-required`
- `\Views\Partials\Forms\Themes\default\Fieldtypes\FieldType.CheckBoxList.cshtml`
Line 12 change `data-val-requiredlist` to `data-val-required`

According to [this topic](https://our.umbraco.com/forum/umbraco-forms/90951-is-there-a-significant-bug-with-forms-radio-button-validation#comment-286938) on the forums.

(This is a Gold partner issue)

**Comment by bergmania** [comment] 2019-05-13 07:30
Hey @SteveVaneeckhout 

I can only reproduce in the `bootstrap3-horizontal` theme, but not in the default theme. 

If I change `data-val-requiredlist` to `data-val-required` in `\Views\Partials\Forms\Themes\default\Fieldtypes\FieldType.CheckBoxList.cshtml`, the client side validation do not execute.

The reason the validation do not hooks in, in the `bootstrap3-horizontal` theme, is because the `input` are not wrapped in a `radiobuttonlist`-class.

Turns out, by using `data-rule-required="true"` and `data-msg-required="The validation error-message"`. It seems to work for both the `FieldType.CheckBoxList.cshtml` and `FieldType.RadioButtonList.cshtml`.

**Comment by SteveVaneeckhout** [comment] 2019-05-13 14:32
> I can only reproduce in the `bootstrap3-horizontal` theme, but not in the default theme.
> 
> If I change `data-val-requiredlist` to `data-val-required` in `\Views\Partials\Forms\Themes\default\Fieldtypes\FieldType.CheckBoxList.cshtml`, the client side validation do not execute.

This is weird. Did you turn off form caching in `\App_Plugins\UmbracoForms\UmbracoForms.config` ?

    <setting key="DisableFormCaching" value="True" />

**Comment by bergmania** [comment] 2019-05-13 15:05
I did not turn off caching - What should this has to do with client side validation?

**Comment by bergmania** [comment] 2019-05-13 15:09
Are you having all the dependencies and do you render the scripts as part of the form macro, or adding them by you self?
https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Prepping-Frontend/

**Comment by warrenbuckley** [comment] 2019-05-29 13:25
Fixed in V7 & V8 PR's

**Closed by warrenbuckley** 2019-05-29 13:25 UTC
Labels: state/backlog
