### ISSUE TITLE
Apostrophe shows as &#x27; in the Entries view

### ISSUE THREAD

**Issue by russellshome** [umbraco/Umbraco.Forms.Issues#699] opened 2022-01-13 22:32 UTC
When viewing the entries of a form which has a name that contains apostrophes, the name is shown with the apostrophe changed to &#x27;

Reproduction
------------

Create a form with the name: Test this form's entries
Save
Click on Entries
The title is: Test this form&#x27;s entries Entries

### Bug summary

The title of the Entries view should start with the name of the form 

### Specifics

Chome and Edge were checked.

![FormsIssue](https://user-images.githubusercontent.com/8239408/149419207-3ea22922-0057-4cfc-96da-1f8b6fab210a.jpg)
### Steps to reproduce

Create a form with the name: Test this form's entries
Save
Click on Entries
The title is: Test this form&#x27;s entries Entries

### Expected result

The title of the Entries view should start with the name of the form 

### Actual result

In the Entires view apostrophe is changed to &#x27;

**Comment by russellshome** [comment] 2022-01-13 22:33
Umbraco version 8.17.1
Current installed version of Umbraco Forms: 8.10.0

**Comment by AndyButland** [comment] 2022-01-14 07:29
Thanks for letting us know @russellshome.  This regression has crept in due to the back-office localization changes introduced in 8.10.  It looks a fairly straightforward fix so we'll get this resolved in the next patch releases.

**Closed** 2022-01-14 07:29 UTC
Labels: release/8.10.1, release/9.2.1
