### ISSUE TITLE
Number of rows is not saved for Long answer

### ISSUE THREAD

**Issue by russellshome** [umbraco/Umbraco.Forms.Issues#544] opened 2021-04-19 21:41 UTC
When "Long Answer"  is used as an answer type, the "Number of Rows" is not saved.

Reproduction
------------

### Bug summary

Create a form with a question and choose "Long Answer" as the answer type.

Set "Number of Rows" to 5.

Submit and Save

Reload the page and click the cog to check the value of "Number of Rows" for that answer type.
You will see that it is blank

### Specifics

v8.7.1
Same result in Edge and Chrome

### Steps to reproduce

see reproduction above

### Expected result

Number of rows is saved

### Actual result

Number of rows is not saved

---
_This item has been added to our backlog [AB#11585](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/11585)_

**Comment by nul800sebastiaan** [comment] 2021-04-21 14:51
Thanks @russellshome for the report! At first I couldn't reproduce this but I realized I had to click out of the form, or indeed reload the page.


https://user-images.githubusercontent.com/304656/115574277-c6a4a980-a2c1-11eb-80cc-aa6310359d3c.mp4

We'll have to have a look!

**Comment by AndyButland** [comment] 2021-05-04 12:02
Resolved in the linked PR and due in 8.7.2,

**Closed** 2021-05-04 12:03 UTC
Labels: release/8.7.2, state/sprint-candidate, type/bug
