### ISSUE TITLE
Workflow improvments around logging and retries

### ISSUE THREAD

**Issue by Matthew-Wise** [umbraco/Umbraco.Forms.Issues#959] opened 2023-01-20 16:17 UTC
Hi,

I am creating a workingflow for sending data to the CRM, I want to be able to  automatically retry the workflow later in the day in case it was a CRM issue, and eventally giving up as it likely a data issue.

It would also be great to have some sort of logging message on the audit log so the client can see the issue without access to the Log Viewer.

The retrying would be possible if the  IWorkflowExecutionService exposed the overload the implomentation has, as I could then use a scheduled background task or hangfire etc. Along with a SQL query to get the failing records/flows.

Happy to chat more on here or other means 

Happy Umbracoing
Matt

**Comment by AndyButland** [comment] 2023-01-23 05:44
Hi @Matthew-Wise - is it `ExecuteWorkflows(List<IWorkflow> workflows, Record record, Form form, FormState state);` you are looking for when you mention the overload?  As that is available on `IWorkflowExecutionService` in Forms 11.  It wasn't in Forms 10 as we couldn't add it without a breaking change, so it's just on the implementation `WorkflowExecutionService`.

Even if using Forms 10 though, you should be able to case to `WorkflowExecutionService` in order to use it in some custom code.

**Comment by Matthew-Wise** [comment] 2023-01-23 09:32
Morning Andy, 
Thanks for the quick response!

Yeah thats the one :), looking at 10.2.2.0 `WorkflowExecutionService` looks to be internal. Not sure yet if the client will be moving to Umbraco 11 of waiting till 13.

**Comment by AndyButland** [comment] 2023-01-23 09:54
That's a good point, we do this casting within the code base but of course can as we can access internal.  So unfortunately I don't see a way we can expose this... we can't add it to the interface as that would be a breaking change.  You could look at some reflection.  There is a risk in doing that that your code could break in a future 10 update... but it seems unlikely, given we've effectively committed to that method signature by adding it to the interface in 11.

**Comment by Matthew-Wise** [comment] 2023-01-23 10:15
One possible option without a breaking change - https://devblogs.microsoft.com/dotnet/default-implementations-in-interfaces/ not sure how you feel about that though.

**Comment by AndyButland** [comment] 2023-01-23 10:48
I don't think that'll work in this case - though do tell me if you think I'm wrong.  As I understand the default implementation needs to call another method on the interface, so it works nicely if you are adding a new overload that for example extends an existing one with an additional parameter.  But I don't think we have a suitable method available in this case.

**Comment by Matthew-Wise** [comment] 2023-01-23 11:04
Yep this is what I get for reading things in a meeting :D Looks like Ill have to do a bit of reflection

**Comment by Matthew-Wise** [comment] 2023-01-23 11:35
I just need to write the SQL query to get the data now.

As above would nice to have a retry system or a query to enable us to do this in future, at least its on the interface for 11 :)

Great work on all the new forms features

**Comment by AndyButland** [comment] 2023-03-01 10:25
I think we'll need to close this, given the issue is resolved in Forms 11, and as discussed it doesn't look to be possible to bring back to Forms 10 without a breaking change.

**Closed by AndyButland** 2023-03-01 10:25 UTC
